<section class="campaign-section-entrants">
    <?php if (empty($this->data)): ?>
        <p>No entrants subscribed yet.</p>
    <?php else: ?>
        <div class="entrants-actions">
            <a href="<?php echo $this->basePath("campaign/exportCsv/{$this->campaign}"); ?>" title="Export as Csv">
                <button type="button">Export as Csv</button>
            </a>
        </div>
        <table>
            <tr>
                <th>Id</th>
                <th>Email</th>
                <th>Referenced By</th>
                <th>Widgets Completed</th>
                <th>Chances Earned</th>
                <th>References Brought</th>
            </tr>
            <?php foreach($this->data as $entrant): ?>
                <tr>
                    <td>
                        <a href="<?php echo $this->basePath("entrant/details/{$entrant['data']['id']}"); ?>" target="_blank">
                            <?php echo $entrant['data']['id']; ?>
                        </a>
                    </td>
                    <td><?php echo $entrant['data']['email']; ?></td>
                    <td><?php echo ($entrant['data']['reference']) ? $entrant['data']['reference'] : '-'; ?></td>
                    <td><?php echo $entrant['widgets']; ?></td>
                    <td><?php echo $entrant['chances']; ?></td>
                    <td><?php echo $entrant['reference']; ?></td>
                </tr>
            <?php endforeach; ?>
        </table>
    <?php endif; ?>
</section>