<section class="campaign-section-widgets">
    <input type="hidden" class="widgets-serialized" name="widgets-serialized" value='<?php echo $this->data['appliedWidgets']; ?>' />
    <div class="applied-widgets"></div>
    <div class="active-widgets">
        <div type="button" class="widget-action-add">
            <i class="fa fa-plus-circle"></i>Add Widgets
        </div>
    </div>
    <div class="available-widgets"></div>
</section>