<section class="campaign-section-prize">
    <input type="hidden" class="prizes-serialized" name="prizes-serialized" value="<?php echo $this->data; ?>"/>
    <div class="prizes"></div>
    <button type="button" class="add-prize-action">
        <i class="fa fa-plus-circle"></i>Add Prize
    </button>
    <script type="text/javascript">
        SpreadPoint.Prize.Controller.init(<?php echo $this->data; ?>);
    </script>
</section>