<section class="campaign-section-widgets">
    <input type="hidden" class="widgets-serialized" name="widgets-serialized" value='<?php echo $this->data['appliedWidgets']; ?>' />
    <div class="applied-widgets"></div>
    <div class="active-widgets">
        <div class="widget-action-add">
            <i class="fa fa-plus-circle"></i>Add Widgets
        </div>
        <div class="available-widgets"></div>
    </div>
</section>
<script type="text/javascript">
    SpreadPoint.FollowTo('.active-widgets', 225);
</script>