<?php

namespace DoctrineORMModule\Proxy\__CG__\Campaign\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Campaign extends \Campaign\Entity\Campaign implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * {@inheritDoc}
     * @param string $name
     */
    public function __get($name)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', array($name));

        return parent::__get($name);
    }

    /**
     * {@inheritDoc}
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', array($name, $value));

        return parent::__set($name, $value);
    }

    /**
     * {@inheritDoc}
     * @param  string $name
     * @return boolean
     */
    public function __isset($name)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__isset', array($name));

        return parent::__isset($name);

    }

    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'user', 'title', 'description', 'startTime', 'endTime', 'banner', 'titleCss', 'descriptionCss', 'status', 'type', 'timezone', 'cycleDuration', 'cyclesCount', 'layout', 'restrictions', 'termsAndConditions', 'showEntrants', 'ageRequirement', 'welcomeEmail', 'winnerEmail', 'sendWelcomeEmail', 'notifyWinners', 'retainPreviousEntrants', 'createdAt');
        }

        return array('__isInitialized__', 'id', 'user', 'title', 'description', 'startTime', 'endTime', 'banner', 'titleCss', 'descriptionCss', 'status', 'type', 'timezone', 'cycleDuration', 'cyclesCount', 'layout', 'restrictions', 'termsAndConditions', 'showEntrants', 'ageRequirement', 'welcomeEmail', 'winnerEmail', 'sendWelcomeEmail', 'notifyWinners', 'retainPreviousEntrants', 'createdAt');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Campaign $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function beforeCreate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'beforeCreate', array());

        return parent::beforeCreate();
    }

    /**
     * {@inheritDoc}
     */
    public function get($property)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'get', array($property));

        return parent::get($property);
    }

    /**
     * {@inheritDoc}
     */
    public function set($property, $value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'set', array($property, $value));

        return parent::set($property, $value);
    }

    /**
     * {@inheritDoc}
     */
    public function beforeSave()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'beforeSave', array());

        return parent::beforeSave();
    }

    /**
     * {@inheritDoc}
     */
    public function beforeUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'beforeUpdate', array());

        return parent::beforeUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function beforeDelete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'beforeDelete', array());

        return parent::beforeDelete();
    }

    /**
     * {@inheritDoc}
     */
    public function afterSave()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'afterSave', array());

        return parent::afterSave();
    }

    /**
     * {@inheritDoc}
     */
    public function afterCreate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'afterCreate', array());

        return parent::afterCreate();
    }

    /**
     * {@inheritDoc}
     */
    public function afterUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'afterUpdate', array());

        return parent::afterUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function afterDelete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'afterDelete', array());

        return parent::afterDelete();
    }

    /**
     * {@inheritDoc}
     */
    public function setData($data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData', array($data));

        return parent::setData($data);
    }

}
