<?php $this->headLink()->appendStylesheet($this->basePath() . '/css/layouts/fullpage-dark.css'); ?>

<div class="campaign-page campaign-fullpage campaign-fullpage-dark">
    <?php echo $this->partial('campaign/layout/parts/fullpage', array(
        'data' => $this->data, 
        'entriesData' => $this->entriesData,
        'prizeData' => $this->prizeData,
        'entrantsCount' => $this->entrantsCount,
        'chancesCount' => $this->chancesCount
    )); ?>
</div>
