<?php $helper = $this->userHelper(); ?>
<div class="upgrade dashboard-section">
    <?php echo $this->partial('user/dashboard/menu.phtml', array('selected' => 'upgrade')); ?>
    
    <div class="upgrade-view dashboard-content">
        <?php $plan = $helper->getLoggedInUser()->get('plan'); ?>
        <?php $order = $helper->getActiveOrder(); ?>
        <div class="checkout-billing checkout-upgrade-plan">
            <?php echo $this->partial('checkout/forms/upgrade.phtml', array('form' => new \Checkout\Model\Form\CheckoutForm(), 'plan' => $plan, 'order' => $order)); ?>
        </div>
    </div>
</div>
<script type="text/javascript">
    SpreadPoint.Checkout.addCurrentPlanValidation(<?php echo $plan; ?>);
    <?php if ($order): ?>
        SpreadPoint.Checkout.addCurrentBillingPeriodValidation('<?php echo (int)($order->get('billingPeriod') === 'Year'); ?>');
    <?php endif; ?>
</script>
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
