<div class="dashboard dashboard-section">
    <?php echo $this->partial('user/dashboard/menu.phtml', array('selected' => 'summary')); ?>
    <div class="dashboard-summary dashboard-content">
        <?php echo $this->partial('application/session/global-messages', array('global_messages' => $this->messages)); ?>
        There is nothing to see here yet. But cool things are coming soon.
    </div>
</div>