<div class="header-login-section">
    <input class="login-action" type="button" value="Sign In">
    <div class="login-form-container hide">
        <div class="login-overlay"></div>
        <section class="login">
            <div class="login-title">
                <div class="title left"><h2>Sign In</h2></div>
                <div class="close right"><span class="close-action">X</span></div>
            </div>
            <?php
                $form = $this->form;
                $form->prepare();
                $form->setAttribute('action', $this->url('account',
                    array('controller'=>'account', 'action' => 'login')));
                $form->setAttribute('method', 'post');
                echo $this->form()->openTag($form);
            ?>
            <div class="login-form custom-form">
                <div class="form-errors"><span class="error"></span></div>
                <?php foreach ($form as $element): ?>
                    <div class="login-form-row custom-form-row custom-row-<?php echo $element->getName(); ?>">
                        <?php echo $this->formElement($element); ?>
                    </div>
                <?php endforeach; ?>
                <div class="login-form-row custom-form-row custom-row-extra forgot-your-password">
                    <a href="<?php echo $this->basePath('account/reset'); ?>" title="Reset Password">Forgot your password?</a>
                </div>
            </div>
            <?php echo $this->form()->closeTag() ?>
        </section>
    </div>
</div>
<script type="text/javascript">
    $(function(){
        var body = $('body');
        var loginOverlay = $('.login-overlay');
        var loginFormContainer = $('.login-form-container');
        
        $('.login-action').on('click', function(){
            loginFormContainer.slideDown(300).prependTo('body');
            loginOverlay.show().on('click', resetScroll).prependTo('body');
            $('.close-action').on('click', resetScroll);
           
            body.addClass('no-scroll');
        });
        
        $('#Login').submit(function(e) {
            e.preventDefault();

            var thisForm = $(this);
            var postData = thisForm.serializeArray();
            var formURL = thisForm.attr("action");

            $.ajax({
                url : formURL,
                data : postData,
                method: "POST"
            }).done(function(data){
                if (data.status) {
                    window.location = "<?php echo $this->basePath('account'); ?>";
                } else {
                    $('.login-form .error').html(data.message);
                }
            });
        });
        
        function resetScroll() 
        {
            body.removeClass('no-scroll');
            loginFormContainer.slideUp(200);            
            loginOverlay.hide();
        }
    });
</script>