<div class="header-login-section">
    <?php if ($this->popup): ?>
        <input class="login-action" type="button" value="Sign In">
    <?php endif; ?>
    <div class="<?php echo ($this->popup) ? 'login-form-popup hide' : 'login-form-container'; ?>">
        <?php echo $this->partial('application/session/global-messages', array('global_messages' => $this->messages)); ?>
        <section class="login">
            <div class="login-title">
                <div class="title left"><h2>Sign In</h2></div>
                <div class="close right"><span class="close-action">X</span></div>
            </div>
            <?php
                $form = $this->form;
                $form->prepare();
                $form->setAttribute('action', $this->url('account',
                    array('controller'=>'account', 'action' => 'auth')));
                $form->setAttribute('method', 'post');
                $form->setAttribute('autocomplete', 'off');
                echo $this->form()->openTag($form);
            ?>
            <?php if ($this->popup): ?>
                <input type="hidden" name="as-json" value="1" />
            <?php endif; ?>
            <div class="login-form custom-form">
                <div class="form-errors"><span class="error"></span></div>
                <?php foreach ($form as $element): ?>
                    <div class="login-form-row custom-form-row custom-row-<?php echo $element->getName(); ?>">
                        <?php echo $this->formElement($element); ?>
                    </div>
                <?php endforeach; ?>
                <div class="login-form-row custom-form-row custom-row-extra forgot-your-password">
                    <a href="<?php echo $this->basePath('account/reset'); ?>" title="Reset Password">Forgot your password?</a>
                </div>
            </div>
            <?php echo $this->form()->closeTag() ?>
        </section>
    </div>
</div>
<script type="text/javascript">
    $(function() {
        SpreadPoint.LoginForm.init();
    });
</script>
