<section class="register">
    <?php
        $form = $this->form;
        $form->prepare();
        $form->setAttribute('action', $this->url('account',
            array('controller'=>'account', 'action' => 'create')));
        $form->setAttribute('method', 'post');
        echo $this->form()->openTag($form);
    ?>
    <div class="register-form custom-form">
        <div class="form-errors"><span class="error"></span></div>
        <?php foreach ($form as $element): ?>
            <div class="register-form-row custom-form-row custom-row-<?php echo $element->getName(); ?>">
                <?php echo $this->formElement($element); ?>
                <?php if (get_class($element) === 'Zend\Form\Element\Checkbox'): ?>
                <label for="terms-and-conditions">
                    I agree to the <a href="<?php echo $this->basePath('terms-of-service'); ?>" title="Terms & Conditions" target="_blank"><strong>Terms & Conditions</strong></a>
                </label>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
    </div>
    <?php echo $this->form()->closeTag() ?>
</section>
<script type="text/javascript">
    $(function() {
        SpreadPoint.RegisterForm.init();
    });
</script>
