<div class="settings dashboard-section">
    <?php echo $this->partial('user/dashboard/menu.phtml', array('selected' => 'settings')); ?>
    <div class="settings-view dashboard-content">
        <form method="post" name="settings" enctype="multipart/form-data" action="<?php echo $this->basePath('/account/save'); ?>" id="settings" novalidate>
            <div class="settings-header">
                <h3 class="left">Settings</h3>
                <div class="settings-actions right">
                    <button type="submit" class="settings-action">
                        <i class="fa fa-save"></i> <span>Save</span>
                    </button>
                </div>
            </div>
            <div class="jqui-tabs-vertical invisible clear">
                <ul class="settings-menu">
                    <li><a href="#notifications">Notifications</a></li>
                </ul>
                <div id="notifications">
                    <?php echo $this->partial('application/session/global-messages', array('global_messages' => $this->messages)); ?>
                    <div class="settings-form-row custom-form-row custom-row-notifications">
                        <div class="field">
                            <label class="notifications left">Enable Notifications</label>
                            <div class="switch">
                                <?php $notification = ($this->user->notifications == 1) ? 'checked' : false; ?>
                                <input class="jqui-switch" name="notifications" type="checkbox" <?php echo $notification; ?> />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>