<?php $helper = $this->campaignHelper(); ?>
<h3 class="widget-title"><?php echo $this->data->title; ?> <span class="chances-count"><i class="fa fa-ticket"></i><?php echo $this->data->earningValue; ?></span></h3>
<div class="widget-content widget-type-entercontest" data-id="<?php echo $this->data->id; ?>">
    <form method="post" name="enter-contest" action="/campaign/enter/<?php echo $this->campaign['id']; ?>" id="enter-contest">
        <input type="hidden" name="id" value="<?php echo $this->data->id?>" />
        <div class="field">
            <input type="text" name="name" class="enter-contest-name" placeholder="Full Name" autocomplete='off' required />
            <input type="email" name="email" class="enter-contest-email" placeholder="Email" autocomplete='off' required />
        </div>
        <?php if ($this->campaign['ageRequirement'] != 1): ?>
            <div class="requirement">
                <input type="checkbox" class="kalypsify" id="ageRequirement" />
                <?php $ageRequirements = $helper->getAllAgeRequirements(); ?>
                <label for="ageRequirement">
                    <?php echo $ageRequirements[$this->campaign['ageRequirement'] - 1 ]['label']; ?>
                </label>
            </div>
        <?php endif; ?>
        <?php if ($campaign['termsAndConditions']): ?>
            <div class="requirement">
                <input type="checkbox" class="kalypsify" id="terms" />
                <label for="terms">
                    I agree to the 
                    <a class="show-terms" href="javascript:void(0);">Terms & Conditions</a>
                </label>
                <div class="terms-box hide">
                    <h2>Terms & Conditions</h2>
                    <textarea readonly><?php echo $campaign['termsAndConditions']; ?></textarea>
                    <button type="button" class="terms-agree">I agree</button>
                    <span class="close"><i class="fa fa-close"></i></span>
                </div>
            </div>
        <?php endif; ?>
        <div class="field">
            <button class="enter-contest-action">Enter Contest</button>
        </div>
    </form>
</div>
<script type="text/javascript">
    SpreadPoint.Front.EnterContest.init();
    SpreadPoint.PopUp.create('.terms-box','.show-terms', '.close', false);
</script>
