<?php $helper = $this->campaignHelper(); ?>
<h3 class="widget-title"><?php echo $this->data->title; ?> <span>+<?php echo $this->data->earningValue; ?></span></h3>
<div class="widget-content widget-type-entercontest" data-id="<?php echo $this->data->id; ?>">
    <form method="post" name="enter-contest" action="/campaign/enter/<?php echo $this->campaign['id']; ?>" id="enter-contest">
        <input type="hidden" name="id" value="<?php echo $this->data->id?>" />
        <div class="field">
            <label>Email</label><input type="email" name="email" class="enter-contest-email" required />
        </div>
        <div class="requirement">
            <?php if ($this->campaign['ageRequirement'] != 1): ?>
                <input type="checkbox" id="ageRequirement" />
                <?php $ageRequirements = $helper->getAllAgeRequirements(); ?>
                <label for="ageRequirement">
                    <?php echo $ageRequirements[$this->campaign['ageRequirement'] - 1 ]['label']; ?>
                </label>
            <?php endif; ?>
        </div>
        <div class="field">
            <button class="enter-contest-action">Enter Contest</button>
        </div>
    </form>
</div>
<script type="text/javascript">
    SpreadPoint.Front.EnterContest.init();
</script>
