<h3 class="widget-title">Enter Contest<span>+<?php echo $this->data->earningValue; ?></span></h3>
<div class="widget-content widget-type-entercontest" data-id="<?php echo $this->data->id; ?>">
    <form method="post" name="enter-contest" action="/campaign/enter/<?php echo $this->campaign; ?>" id="enter-contest">
        <input type="hidden" name="id" value="<?php echo $this->data->id?>" />
        <div class="field">
            <label>Email</label><input type="email" name="email" class="enter-contest-email" required />
        </div>
        <div class="field">
            <button class="enter-contest-action">Enter Contest</button>
        </div>
    </form>
</div>