<h3 class="widget-title">Like Our Page On Facebook
    <?php if (!$this->data->completed): ?>
        <span class="chances">+<?php echo $this->data->earningValue; ?></span>
    <?php endif; ?>
    <span class="completed <?php if (!$this->data->completed) { echo 'hide'; } ?>">
        <i class="fa fa-check"></i>
    </span>
</h3>
<div class="widget-content widget-type-entercontest" data-id="<?php echo $this->data->id; ?>">
    <div class="fb-page" data-href="<?php echo $this->data->page; ?>" 
         data-width="400" 
         data-height="100" 
         data-small-header="true" 
         data-adapt-container-width="true" 
         data-hide-cover="false" 
         data-show-facepile="false" 
         data-show-posts="false">
    </div>
</div>