<h3 class="widget-title">Share a Link On Facebook
    <?php if (!$this->data->completed): ?>
        <span class="chances">+<?php echo $this->data->earningValue; ?></span>
    <?php endif; ?>
    <span class="completed <?php if (!$this->data->completed) { echo 'hide'; } ?>">
        <i class="fa fa-check"></i>
    </span>
</h3>
<div class="widget-content widget-type-facebookshare" data-id="<?php echo $this->data->id; ?>">
    <a href="<?php echo $this->data->link; ?>" class='facebook-share-widget' title="<?php echo $this->data->title; ?>">
        <?php echo $this->data->title; ?>
    </a>
</div>
