<h3 class="widget-title"><?php echo $this->data->title; ?>
    <?php if (!$this->data->completed): ?>
        <span class="chances">
            <span class="chances-count">
                <i class="fa fa-ticket"></i>
                <?php echo $this->data->earningValue; ?>
            </span>
        </span>
    <?php endif; ?>
    <span class="completed <?php if (!$this->data->completed) { echo 'hide'; } ?>">
        <span class="chances-count">
            <i class="fa fa-check"></i>
        </span>
    </span>
</h3>
<div class="widget-content widget-type-facebookshare" data-id="<?php echo $this->data->id; ?>">
    <span class="widget-description">Earn <?php echo $this->data->earningValue; ?> additional chance<?php if ($this->data->earningValue > 1) { echo 's'; }; ?> for sharing a link on facebook.</span>
    <a href="<?php echo $this->data->link; ?>" class='facebook-share-widget' title="<?php echo $this->data->title; ?>">
        <button><?php echo $this->data->title; ?><i class="fa fa-external-link"></i></button>
    </a>
</div>
