<?php $helper = $this->campaignHelper(); ?>
<h3 class="widget-title"><?php echo $this->data->title; ?>
    <span class="chances-count">
        <i class="fa fa-ticket"></i>
        <?php echo $this->data->earningValue; ?>
    </span>
</h3>
<div class="widget-content widget-type-reference" data-id="<?php echo $this->data->id; ?>">
    <?php $domain = $helper->getDomain(); ?>
    <?php $entrant = $helper->getEntrantId(); ?>
    
    <?php $referenceUrl = "{$domain}/campaign/reference/{$entrant}"; ?>
    <?php $subject = "Check this out!"; ?>
    <?php $content = "I found a great contest, check it out: "; ?>
    
    <input type="text" readonly onclick="this.select()" value="<?php echo $referenceUrl; ?>" size='35' />
    <div class="sharing-options">
        <div class="option fb-share-button" data-href="<?php echo $referenceUrl; ?>" data-layout="button"></div>
        <div class="option twitter-tweet">
            <a class="twitter-share-button" data-size="medium" data-count="none" href="https://twitter.com/intent/tweet?url=<?php echo $referenceUrl; ?>&text=<?php echo $content; ?>">
                Tweet
            </a>
        </div>
        <div class="option send-email">
            <a href="mailto:?subject=<?php echo $subject; ?>&body=<?php echo $content . $referenceUrl; ?>">
                <button>
                    <i class="fa fa-envelope"></i>Email
                </button>
            </a>
        </div>
    </div>
</div>