<?php $helper = $this->campaignHelper(); ?>
<h3 class="widget-title">Tell your Friends<span>+<?php echo $this->data->earningValue; ?></span></h3>
<div class="widget-content widget-type-reference" data-id="<?php echo $this->data->id; ?>">
    <?php $domain = $helper->getDomain(); ?>
    <?php $entrant = $helper->getEntrantId(); ?>
    <input type="text" readonly onclick="this.select()" value="<?php echo "{$domain}/campaign/reference/{$entrant}"; ?>" />
</div>