<h3 class="widget-title">Follow us on Twitter
    <?php if (!$this->data->completed): ?>
        <span class="chances">+<?php echo $this->data->earningValue; ?></span>
    <?php endif; ?>
    <span class="completed <?php if (!$this->data->completed) { echo 'hide'; } ?>">
        <i class="fa fa-check"></i>
    </span>
</h3>
<div class="widget-content widget-type-twitterfollow" data-id="<?php echo $this->data->id; ?>">
    <a class="twitter-follow-button" href="https://twitter.com/<?php echo $this->data->user; ?>" data-size="large">Follow @<?php $this->data->user; ?></a>
</div>
