<h3 class="widget-title"><?php echo $this->data->title; ?>
    <?php if (!$this->data->completed): ?>
        <span class="chances">
            <span class="chances-count">
                <i class="fa fa-ticket"></i>
                <?php echo $this->data->earningValue; ?>
            </span>
        </span>
    <?php endif; ?>
    <span class="completed <?php if (!$this->data->completed) { echo 'hide'; } ?>">
        <span class="chances-count">
            <i class="fa fa-check"></i>
        </span>
    </span>
</h3>
<div class="widget-content widget-type-twitterfollow" data-id="<?php echo $this->data->id; ?>">
    <a class="twitter-follow-button" data-count="none" href="https://twitter.com/<?php echo $this->data->user; ?>" data-size="large">Follow @<?php $this->data->user; ?></a>
</div>
