<div class="page-404">
    <div class="sky">
        <div class="cloud cloud-1"></div>
        <div class="cloud cloud-2"></div>
        <div class="moon hide-on-portrait"></div>
        <div class="blob"></div>
    </div>
    <div class="ocean">
        <div class="upper-waves waves"></div>
        <div class="bottom-wawes waves"></div>
    </div>
    <div class="sand">
        <div class="ghettoblaster hide-on-portrait"></div>
    </div>
    <div class="tree"></div>
    <a href="<?php echo $this->basePath(''); ?>" title="Home"><div class="sign"></div></a>
</div>