<body style="margin: 0; background-color: #F1F3F4; width: 100%; height: 100%;">
    <div class="content" style="background-color: white; width: 600px; margin: 0 auto; margin-top: 25px; border: 1px solid #e7e8e9; padding: 10px 0 25px 0; border-radius: 5px; ">
        <div class="header" style="margin-bottom: 20px; text-align: center; background-color: #473E3F; padding-top: 3px;">
            <img src="<?php echo $this->basePath('img/logo.png'); ?>" alt="SpreadPoint" width="150" />
        </div>
        <div class="body" style="padding: 0 20px;">
            <?php echo $this->body; ?>
        </div>
    </div>
</body>