<?php $campaignHelper = $this->campaignHelper(); ?>
<?php $campaignHelper->setData($this->data); ?>
<div class="campaigns dashboard-section">
    <?php echo $this->partial('user/dashboard/menu.phtml', array('selected' => 'campaigns')); ?>
    <div class="campaign-view dashboard-content">
        <?php echo $this->partial('application/session/global-messages', array('global_messages' => $this->messages)); ?>
        <?php $savePath = '/campaign/save/'; ?>
        <?php $savePath .= $campaignHelper->get('id'); ?>
        <form method="post" name="campaign" enctype="multipart/form-data" action="<?php echo $savePath; ?>" id="campaign" novalidate>
            <div class="campaign-view-header dashboard-header">
                <div class="campaign-view-title dashboard-title left">
                    <?php $title = $campaignHelper->get('title'); ?>
                    <h2><?php echo ($title) ? $title : 'New Campaign'; ?></h2>
                    <?php if ($campaignHelper->get('status')): ?>
                    <span class="status status-<?php echo strtolower($campaignHelper->getStatusString()); ?>">( <span class="status-dot"></span> <?php echo $campaignHelper->getStatusString(); ?> )</span>
                    <?php endif; ?>
                </div>
                <div class="campaign-view-actions right">
                    <?php if (array_key_exists('id', $this->data) && $campaignHelper->getToggledStatus()): ?>
                        <?php $url = 'campaign/updateStatus/' . $this->data['id'] . '/status/' . $campaignHelper->getToggledStatus(); ?>
                    <a href="<?php echo $this->basePath($url); ?>" title="<?php echo $campaignHelper->getToggledStatusTitle(); ?> Campaign" class="action-<?php echo strtolower($campaignHelper->getToggledStatusTitle()); ?>">
                            <button type="button" class="campaign-view-action campaign-view-toggle-status">
                                <i class="fa <?php echo $campaignHelper->getToggledStatusIcon(); ?>"></i> <?php echo $campaignHelper->getToggledStatusTitle(); ?>
                            </button>
                        </a>
                    <?php endif; ?>
                    <a href="javascript:void(0);" title="Save">
                        <button type="submit" class="campaign-view-action campaign-view-save">
                            <i class="fa fa-save"></i> Save
                        </button>
                    </a>
                    <a href="<?php echo $this->basePath('campaigns'); ?>" title="Cancel">
                        <button type="button" class="campaign-view-action campaign-view-cancel">
                            <i class="fa fa-undo"></i> Cancel
                        </button>
                    </a>
                </div>
            </div>
            <div class="campaign-view-content">
                <div class="campaign-tabs jqui-tabs invisible">
                    <ul>
                        <?php if (array_key_exists('id', $this->data)): ?>
                            <li><a href="#overview" class="overview-tab">Overview</a></li>
                        <?php endif; ?>
                        <li><a href="#general" class="general-tab">General</a></li>
                        <li><a href="#schedule" class="schedule-tab">Schedule</a></li>
                        <li><a href="#widgets" class="entries-tab">Widgets</a></li>
                        <li><a href="#prize" class="prize-tab">Prizes</a></li>                        
                        <li><a href="#advanced" class="advanced-tab">Advanced</a></li>
                        <?php if (array_key_exists('id', $this->data)): ?>
                            <li><a href="#entrants" class="entrant-tab">Entrants</a></li>
                            <li><a href="#winners" class="winner-tab">Winners</a></li>
                        <?php endif; ?>
                    </ul>
                    <?php if (array_key_exists('id', $this->data)): ?>
                        <div id="overview" class="campaign-tab">
                            <?php echo $this->partial('campaign/sections/overview.phtml', array('data' => $this->data, 'social' => $this->social)); ?>
                        </div>
                    <?php endif; ?>
                    <div id="general" class="campaign-tab">
                        <?php echo $this->partial('campaign/sections/general.phtml', array('data' => $this->data)); ?>
                    </div>
                    <div id="schedule" class="campaign-tab">
                        <?php echo $this->partial('campaign/sections/schedule.phtml', array('data' => $this->data)); ?>
                    </div>
                    <div id="widgets" class="campaign-tab">
                        <?php echo $this->partial('campaign/sections/widgets.phtml', array('data' => $this->entriesData)); ?>
                    </div>
                    <div id="prize" class="campaign-tab">
                        <?php echo $this->partial('campaign/sections/prize.phtml', array('data' => $this->prizesData)); ?>
                    </div>
                    <div id="advanced" class="campaign-tab">
                        <?php echo $this->partial('campaign/sections/advanced.phtml', array('data' => $this->data)); ?>
                    </div>
                    <?php if (array_key_exists('id', $this->data)): ?>
                        <div id="entrants" class="campaign-tab">
                            <?php echo $this->partial('campaign/sections/entrants.phtml', array('data' => $this->entrantsData, 'campaign' => $campaignHelper->get('id'))); ?>
                        </div>
                        <div id="winners" class="campaign-tab">
                            <?php echo $this->partial('campaign/sections/winners.phtml', array(
                                'data' => $this->winnersData, 
                                'prizes' => $this->prizesData, 
                                'entrants' => $this->entrantsData,
                                'campaign' => $this->data
                            )); ?>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </form>
    </div>
</div>
<script type="text/javascript">
    $(function(){
        SpreadPoint.Uploader.init('.custom-row-banner .file-upload', 'banner');
        SpreadPoint.Campaign.Controller.init(
            <?php echo $this->entriesData['widgetTypes']; ?>, 
            <?php echo $this->entriesData['appliedWidgets']; ?>,
            <?php echo $this->prizesData; ?>,
            '<?php echo $campaignHelper->getBaseImagePath($campaignHelper->get('id')); ?>'
        );
    });
</script>