<?php $campaignHelper = $this->campaignHelper(); ?>
<?php $campaignHelper->setData($this->data); ?>
<div class="campaigns dashboard-section">
    <?php echo $this->partial('user/dashboard/menu.phtml', array('selected' => 'campaigns')); ?>
    <div class="campaign-view dashboard-content">
        <?php echo $this->partial('application/session/global-messages', array('global_messages' => $this->messages)); ?>
        <?php $savePath = '/campaign/save/'; ?>
        <?php $savePath .= $campaignHelper->get('id'); ?>
        <form method="post" name="campaign" enctype="multipart/form-data" action="<?php echo $savePath; ?>" id="campaign" novalidate>
            <div class="campaign-view-header dashboard-header">
                <div class="campaign-view-title dashboard-title left">
                    <?php $title = $campaignHelper->get('title'); ?>
                    <h2><?php echo ($title) ? $title : 'New Campaign'; ?> 
                        <?php if ($campaignHelper->get('status')): ?>
                            (<?php echo $campaignHelper->getStatusString(); ?>)
                        <?php endif; ?>
                    </h2>
                </div>
                <div class="campaign-view-actions right">
                    <?php if (array_key_exists('id', $this->data) && $campaignHelper->getToggledStatus()): ?>
                        <?php $url = 'campaign/updateStatus/' . $this->data['id'] . '/status/' . $campaignHelper->getToggledStatus(); ?>
                        <a href="<?php echo $this->basePath($url); ?>" title="<?php echo $campaignHelper->getToggledStatusTitle(); ?> Campaign">
                            <button type="button" class="campaign-view-action campaign-view-toggle-status">
                                <i class="fa <?php echo $campaignHelper->getToggledStatusIcon(); ?>"></i> <?php echo $campaignHelper->getToggledStatusTitle(); ?>
                            </button>
                        </a>
                    <?php endif; ?>
                    <button type="submit" class="campaign-view-action campaign-view-save">
                        <i class="fa fa-save"></i> Save
                    </button>
                    <a href="<?php echo $this->basePath('campaigns'); ?>" title="Cancel">
                        <button type="button" class="campaign-view-action campaign-view-cancel">
                            <i class="fa fa-undo"></i> Cancel
                        </button>
                    </a>
                    <a href="<?php echo $this->basePath('campaign/preview'); ?>" title="Preview">
                        <button type="button" class="campaign-view-action campaign-view-preview">
                            <i class="fa fa-eye"></i> Preview
                        </button>
                    </a>
                </div>
            </div>
            <div class="campaign-view-content">
                <div class="campaign-tabs jqui-tabs">
                    <ul>
                        <li><a href="#general" class="general-tab">General</a></li>
                        <li><a href="#schedule" class="schedule-tab">Schedule</a></li>
                        <li><a href="#entries" class="entries-tab">Entries</a></li>
                        <li><a href="#prize" class="prize-tab">Prizes</a></li>                        
                        <li><a href="#advanced" class="advanced-tab">Advanced</a></li>
                    </ul>
                    <div id="general" class="campaign-tab">
                        <?php echo $this->partial('campaign/sections/general.phtml', array('data' => $this->data)); ?>
                    </div>
                    <div id="schedule" class="campaign-tab">
                        <?php echo $this->partial('campaign/sections/schedule.phtml', array('data' => $this->data)); ?>
                    </div>
                    <div id="entries" class="campaign-tab">
                        <?php echo $this->partial('campaign/sections/entries.phtml', array('data' => $this->entriesData)); ?>
                    </div>
                    <div id="prize" class="campaign-tab">
                        <?php echo $this->partial('campaign/sections/prize.phtml', array('data' => $this->prizesData)); ?>
                    </div>
                    <div id="advanced" class="campaign-tab">
                        <?php echo $this->partial('campaign/sections/advanced.phtml', array('data' => $this->data)); ?>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<script type="text/javascript">
    $(function(){
        SpreadPoint.Uploader.init('.custom-row-banner .file-upload', 'banner');
        SpreadPoint.Campaign.Controller.init(
            <?php echo $this->entriesData['widgetTypes']; ?>, 
            <?php echo $this->entriesData['appliedWidgets']; ?>,
            <?php echo $this->prizesData; ?>,
            '<?php echo $campaignHelper->getBaseImagePath($campaignHelper->get('id')); ?>'
        );
    });
</script>