<?php $campaignHelper = $this->campaignHelper(); ?>
<div class="entrants-listing dashboard-section">
    <?php echo $this->partial('user/dashboard/menu.phtml', array('selected' => 'entrants')); ?>
    <div class="entrants-wrapper dashboard-content">
        <div class="entrants-actions">
            <a href="<?php echo $this->basePath('campaign/exportCsv/'); ?>" title="Export as Csv">
                <button type="button">Export as Csv</button>
            </a>
        </div>
        <?php if (empty($this->entrants)): ?>
            <p>No entrants subscribed yet.</p>
        <?php else: ?>
            <table>
                <tr>
                    <th>Id</th>
                    <th>Campaign Id</th>
                    <th>Email</th>
                    <th>Referenced By</th>
                    <th>Widgets Completed</th>
                    <th>Chances Earned</th>
                    <th>References Brought</th>
                </tr>
                <?php foreach($this->entrants as $entrant): ?>
                    <tr>
                        <td><?php echo $entrant['data']['id']; ?></td>
                        <td>
                            <a href="<?php echo $this->basePath("campaign/edit/{$entrant['data']['campaign']}"); ?>">
                                <?php echo $entrant['data']['campaign']; ?>
                            </a>
                        </td>
                        <td><?php echo $entrant['data']['email']; ?></td>
                        <td><?php echo ($entrant['data']['reference']) ? $entrant['data']['reference'] : '-'; ?></td>
                        <td><?php echo $entrant['widgets']; ?></td>
                        <td><?php echo $entrant['chances']; ?></td>
                        <td><?php echo $entrant['reference']; ?></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        <?php endif; ?>
    </div>
</div>
