<?php $helper = $this->campaignHelper(); ?>
<div class="campaign-container">
    <?php if ($this->data['status'] == \Campaign\Entity\Campaign::STATUS_ACTIVE): ?>
        <?php echo $this->partial($helper->getLayout($this->data['layout']), array(
            'data' => $this->data, 
            'entriesData' => $this->entriesData,
            'prizeData' => $this->prizesData
        )); ?>
    <?php else: ?>
        <span>This contest is not active right now.</span>
    <?php endif; ?>
</div>

<!-- Facebook Scripts -->

<div id="fb-root"></div>
<script>
    window.fbAsyncInit = function() {
        FB.init({
            appId      : '711375515639582',
            xfbml      : true,
            version    : 'v2.4'
        });
        
        SpreadPoint.Front.Facebook.load();
    };

    (function(d, s, id){
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) {return;}
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js";
        fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

<script>
    window.twttr = (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0],
        t = window.twttr || {};
        if (d.getElementById(id)) return t;
        js = d.createElement(s);
        js.id = id;
        js.src = "https://platform.twitter.com/widgets.js";
        fjs.parentNode.insertBefore(js, fjs);

        t._e = [];
        t.ready = function(f) {
            t._e.push(f);
        };
 
        return t;
    }(document, "script", "twitter-wjs"));
    
    twttr.ready(function (twttr) {
        SpreadPoint.Front.Twitter.load();
    });
</script>