<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('SpreadPoint - Start Generating New Leads'); ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->appendStylesheet('//fonts.googleapis.com/css?family=Open+Sans%3A400%2C300%2C400italic%2C600%2C700')
            ->appendStylesheet($this->basePath() . '/css/sensible/fonts/font-awesome.css')
            ->appendStylesheet($this->basePath() . '/css/kalypto.css')
        ;?>
        
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->appendFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
            ->appendFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->appendFile($this->basePath() . '/js/jquery-1.11.3.min.js')
            ->appendFile($this->basePath() . '/js/jquery-ui.js')
            ->appendFile($this->basePath() . '/js/handlebars-v3.0.3.js')
            ->appendFile($this->basePath() . '/js/bootstrap.min.js')
            ->appendFile($this->basePath() . '/js/kalypto.min.js')
            ->appendFile($this->basePath() . '/js/assets/templates.js')
            ->appendFile($this->basePath() . '/js/assets/scripts.js')
            ->appendFile($this->basePath() . '/js/assets/campaign.js')
        ;?>

        <?php $analytics = $this->configHelper()->get('google-analytics'); ?>
        <?php if ($analytics['enabled']): ?>
            <!-- Google Analytics -->
            <script>
                (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
                })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

                ga('create', '<?php echo $analytics['app-id']; ?>', 'auto');
                ga('send', 'pageview');
            </script>
        <?php endif; ?>
        
    </head>
    <body>
        <div class="container">
            <?php echo $this->content; ?>         
        </div>
        <?php echo $this->inlineScript(); ?>
    </body>
</html>
