<?php use User\Model\Form\LoginForm; ?>
<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('SpreadPoint - Start Generating New Leads'); ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->appendStylesheet($this->basePath() . '/css/style.css')
            ->appendStylesheet($this->basePath() . '/css/sensible/style.css')
            ->appendStylesheet('//fonts.googleapis.com/css?family=Open+Sans%3A400%2C300%2C400italic%2C600%2C700')
            ->appendStylesheet($this->basePath() . '/css/sensible/fonts/font-awesome.css')
            ->appendStylesheet($this->basePath() . '/css/sensible/jPushMenu.css')
            ->appendStylesheet($this->basePath() . '/css/sensible/animate.css')
        
        ;?>
        
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->appendFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
            ->appendFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->appendFile($this->basePath() . '/js/jquery-1.11.3.min.js')
            ->appendFile($this->basePath() . '/js/bootstrap.min.js')
            ->appendFile($this->basePath() . '/js/sensible/wow.js')
            ->appendFile($this->basePath() . '/js/sensible/wow-init.js')
            ->appendFile($this->basePath() . '/js/sensible/parallax.js')
            ->appendFile($this->basePath() . '/js/sensible/jPushMenu.js')
            ->appendFile($this->basePath() . '/js/scripts.js')
        ;?>

        <!-- Google Analytics -->
        <!--
        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

            ga('create', 'UA-62958605-2', 'auto');
            ga('send', 'pageview');
        </script>
        -->
        
    </head>
    <body>
        <header id="masthead" class="site-header" role="banner">
            <div class="transparent-overlay"></div>
            <div class="grid grid-pad head-overflow">
                <div class="site-branding">
                    <div class="site-logo">
                        <a href="<?php echo $this->serverUrl(); ?>" title="SpreadPoint">
                            <img src="<?php echo $this->basePath('img/logo.png') ?>" alt="SpreadPoint">
                        </a>
                    </div>
                </div>
                <div class="navigation-container">
                    <nav id="site-navigation" class="main-navigation" role="navigation">
                        <button class="menu-toggle toggle-menu menu-right push-body jPushMenuBtn">
                            <i class="fa fa-bars"></i> 
                            Menu
                        </button>
                        <div class="menu-container">
                            <ul id="menu" class="menu nav-menu">
                                <li id="menu-item-1" class="menu-item menu-item-type-post_type menu-item-object-page">
                                    <a href="<?php echo $this->basePath('pricing'); ?>" class="menu-item-link">Pricing</a>
                                </li>
                                <li id="menu-item-2" class="menu-item menu-item-type-post_type menu-item-object-page">
                                    <a href="<?php echo $this->basePath("contact"); ?>" class="menu-item-link">Talk to us</a>
                                </li>
                                <li id="menu-item-3" class ="menu-item menu-item-type-post_type menu-item-object-page">
                                    <div class="header-account-container">
                                        <?php $isLoggedIn = $this->userHelper()->isLoggedIn(); ?>
                                        <?php if ($isLoggedIn): ?>
                                            <div class="header-account-section">
                                                <a href="<?php echo $this->basePath('account'); ?>" class="menu-item-link account-username">
                                                    <i class="fa fa-user"></i>
                                                    <?php echo $this->userHelper()->getUsername(); ?>
                                                </a>
                                                <ul class="account-links hide">
                                                    <li class="first">
                                                        <a href="<?php echo $this->basePath('account'); ?>" class="account-dashboard first">
                                                            <i class="fa fa-dashboard"></i> Dashboard
                                                        </a>
                                                    </li>
                                                    <li>
                                                        <a href="<?php echo $this->basePath('account/billing'); ?>" class="account-billing">
                                                            <i class="fa fa-dollar"></i> Billing
                                                        </a>
                                                    </li>
                                                    <li>
                                                        <a href="<?php echo $this->basePath('account/settings'); ?>" class="account-settings">
                                                            <i class="fa fa-gear"></i> Settings
                                                        </a>
                                                    </li>
                                                    <li>
                                                        <a href="<?php echo $this->basePath('account/upgrade'); ?>" class="account-upgrade">
                                                            <i class="fa fa-arrow-up"></i> Upgrade
                                                        </a>
                                                    </li>
                                                    <li>
                                                        <a href="<?php echo $this->basePath('account/support'); ?>" class="account-support">
                                                            <i class="fa fa-support"></i> Support
                                                        </a>
                                                    </li>
                                                    <li class="last">
                                                        <a href="<?php echo $this->basePath('account/logout'); ?>" class="account-logout last">
                                                            <i class="fa fa-power-off"></i> Log Out
                                                        </a>
                                                    </li>
                                                </ul>
                                            </div>
                                        <?php else: ?>
                                            <?php echo $this->partial('user/account/login.phtml', array('form' => new LoginForm())); ?>
                                        <?php endif; ?>
                                    </div>
                                </li>
                            </ul>
                        </div> 
                    </nav>
                </div>
            </div>
        </header>
        
        <nav class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-right">
            <h3>Menu</h3> 
            <div class="menu-container">
                <ul id="menu" class="menu">
                    <li id="menu-item-1" class="menu-item menu-item-type-post_type menu-item-object-page">
                        <a href="<?php echo $this->basePath('pricing'); ?>">Pricing</a>
                    </li>
                    <li id="menu-item-2" class="menu-item menu-item-type-post_type menu-item-object-page">
                        <a href="javascript:void(0);">Login</a>
                    </li>
                    <li id="menu-item-3" class="menu-item menu-item-type-post_type menu-item-object-page">
                        <a href="javascript:void(0);">Register</a>
                    </li>
                    <li id="menu-item-4" class="menu-item menu-item-type-post_type menu-item-object-page">
                        <a href="<?php echo $this->basePath("contact"); ?>">Talk to us</a>
                    </li>
                </ul>
            </div> 
        </nav>
        
        <div class="container">
            <?php echo $this->content; ?>            
        </div>
        
        <footer id="colophon" class="site-footer" role="contentinfo">
            <div class="grid grid-pad">
                <div class="site-info col-1-1">
                    <p>&copy;<?php echo date('Y'); ?> SpreadPoint. All rights reserved.</p>
                </div>
            </div>
        </footer>
        
        <script type="text/javascript">
            $(function() {
                var defaults = new SpreadPoint.Defaults();
                defaults.callFunctions();
            });
        </script>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
