<?php use Checkout\Helper\PlanHelper; ?>
<?php $helper = $this->planHelper(); ?>
<?php $plans = $helper->getAllPlans(); ?>

<?php $stripe = $this->configHelper()->get('stripe'); ?>
<?php $publishableKey = ($stripe['test_mode']) ? $stripe['test_publishable'] : $stripe['live_publishable']; ?>

<script type="text/javascript" src="https://js.stripe.com/v2/"></script>

<section class="checkout-section">
    <?php
        $form = $this->form;
        $form->prepare();
        $form->setAttribute('action', $this->url('checkout',
            array('controller'=>'cart', 'action' => 'submit')));
        $form->setAttribute('method', 'post');
        $form->setAttribute('novalidate', 'novalidate');
        echo $this->form()->openTag($form);
    ?>
    
    <div class="checkout-form custom-form plan-form">
        <?php echo $this->partial('application/session/global-messages', array('global_messages' => $this->messages)); ?>
        <div class="subtitle">
            <h4>Plan</h4>
        </div>
        <div class="checkout-form-row custom-form-row custom-row-plan">
            <div class="hidden-plan-element hide">
                <?php echo $this->formElement($form->get('plan')->setValue($this->plan)); ?>
            </div>
            <div class="visible-plan element">
                <div class="plan-puddle checkout-plan" data-value="<?php echo PlanHelper::PUDDLE_PLAN;?>">
                    <span class="title"><?php echo ucfirst($plans[PlanHelper::PUDDLE_PLAN]['name']); ?></span>
                    <a  href="javascript:void(0);" class="puddle-plan-trigger" title="<?php echo $plans[PlanHelper::PUDDLE_PLAN]['name'] ;?> Plan">
                        <img src="<?php echo $this->basePath($plans[PlanHelper::PUDDLE_PLAN]['image']); ?>" alt="<?php echo $plans[PlanHelper::PUDDLE_PLAN]['name'] ;?> Plan" width="100" height="100" />
                    </a>
                    <span class="price">$<?php echo ucfirst($plans[PlanHelper::PUDDLE_PLAN]['monthly']) ;?>/mo</span>
                    <span class="price">$<?php echo ucfirst($plans[PlanHelper::PUDDLE_PLAN]['yearly']) ;?>/yr</span>
                </div>
                <div class="plan-lake checkout-plan" data-value="<?php echo PlanHelper::LAKE_PLAN;?>">
                    <span class="title"><?php echo ucfirst($plans[PlanHelper::LAKE_PLAN]['name']); ?></span>                    
                    <a  href="javascript:void(0);" class="lake-plan-trigger" title="<?php echo $plans[PlanHelper::LAKE_PLAN]['name'] ;?> Plan">
                        <img src="<?php echo $this->basePath($plans[PlanHelper::LAKE_PLAN]['image']); ?>" alt="<?php echo $plans[PlanHelper::LAKE_PLAN]['name'] ;?> Plan" width="100" height="100" />
                    </a>
                    <span class="price">$<?php echo ucfirst($plans[PlanHelper::LAKE_PLAN]['monthly']) ;?>/mo</span>
                    <span class="price">$<?php echo ucfirst($plans[PlanHelper::LAKE_PLAN]['yearly']) ;?>/yr</span>
                </div>
                <div class="plan-ocean checkout-plan" data-value="<?php echo PlanHelper::OCEAN_PLAN;?>">
                    <span class="title"><?php echo ucfirst($plans[PlanHelper::OCEAN_PLAN]['name']); ?></span>
                    <a href="javascript:void(0);" class="ocean-plan-trigger" title="<?php echo $plans[PlanHelper::OCEAN_PLAN]['name'] ;?> Plan">
                        <img src="<?php echo $this->basePath($plans[PlanHelper::OCEAN_PLAN]['image']); ?>" alt="<?php echo $plans[PlanHelper::OCEAN_PLAN]['name'] ;?> Plan" width="90" height="90" />
                    </a>
                    <span class="price">Custom</span>
                    <span class="price">Price</span>
                </div>
            </div>
            <div class="period-element element">
                <div class="row row-label">
                    <label class="period-label"><i class="fa fa-calendar"></i>Billing Period:</label>
                </div>
                <div class="row row-check">
                    <input id="monthly" type="radio" name="period" required="required" class="kalypsify" value="0">
                    <label for="monthly">Monthly</label>
                </div>
                <div class="row row-check">
                    <input id="yearly" type="radio" name="period" required="required" class="kalypsify" value="1">
                    <label for="yearly">Yearly</label>            
                </div>
            </div>
        </div>
    </div>
    
    <div class="checkout-form custom-form checkout-payment-form">
        <div class="subtitle">
            <h4 class="left">Card</h4>
            <span class="pay-pal-text right">or pay with <span class="pay-pal-action greyscale"></span></span>
        </div>
        <div class="checkout-form-row custom-form-row custom-row-fullname">
            <input required="required" placeholder="Full name on credit card" autocomplete="off" type="text" data-stripe="name" />
        </div>
        <div class="checkout-form-row custom-form-row custom-row-card_number">
            <input class="real-card" required="required" maxlength="20" type="hidden" data-stripe="number" />
            <input required="required" placeholder="Card Number" maxlength="19" autocomplete="off" type="text" />
        </div>
        <div class="checkout-form-row custom-form-row custom-row-expiry_date">
            <input required="required" class="expiry-month" maxlength="2" type="hidden" data-stripe="exp-month" />
            <input required="required" class="expiry-year" maxlength="4" type="hidden" data-stripe="exp-year" />
            <input required="required" placeholder="MM/YY" maxlength="7" autocomplete="off" type="text" />
        </div>
        <div class="checkout-form-row custom-form-row custom-row-cvc">
            <input required="required" placeholder="CVC" maxlength="4" autocomplete="off" type="text"  data-stripe="cvc" />
        </div>
        <div class="checkout-form-row custom-form-row custom-row-submit-action">
            <img class="loader hide" src="/img/loading.gif" alt="Loading" width="40" />
            <input type="submit" class="checkout-submit" value="Pay Now">
        </div>
    </div>
    <?php echo $this->form()->closeTag() ?>
</section>
<script type="text/javascript">
    $(function(){
        Stripe.setPublishableKey('<?php echo $publishableKey; ?>');
        SpreadPoint.Checkout.init();
    });
</script>