<section class="checkout-section">
    <?php
        $form = $this->form;
        $form->prepare();
        $form->setAttribute('action', $this->url('checkout',
            array('controller'=>'cart', 'action' => 'submit')));
        $form->setAttribute('method', 'post');
        $form->setAttribute('novalidate', 'novalidate');
        echo $this->form()->openTag($form);
    ?>
    
    <div class="checkout-form custom-form plan-form">
        <?php echo $this->partial('application/session/global-messages', array('global_messages' => $this->messages)); ?>
        <div class="subtitle">
            <h4>Plan</h4>
        </div>
        <div class="checkout-form-row custom-form-row custom-row-plan">
            <div class="hidden-plan-element hide">
                <?php echo $this->formElement($form->get('plan')->setValue($this->plan)); ?>
            </div>
            <div class="visible-plan element">
                <div class="plan-puddle checkout-plan" data-value="0">
                    <span class="title">Puddle</span>
                    <a  href="javascript:void(0);" class="puddle-plan-trigger" title="Puddle Plan">
                        <img src="<?php echo $this->basePath('img/puddle.png'); ?>" alt="Puddle Plan" width="100" height="100" />
                    </a>
                    <span class="price">$29/mo</span>
                </div>
                <div class="plan-lake checkout-plan" data-value="1">
                    <span class="title">Lake</span>                    
                    <a  href="javascript:void(0);" class="lake-plan-trigger" title="Lake Plan">
                        <img src="<?php echo $this->basePath('img/lake.png'); ?>" alt="Lake Plan" width="100" height="100" />
                    </a>
                    <span class="price">$129/mo</span>
                </div>
                <div class="plan-ocean checkout-plan" data-value="2">
                    <span class="title">Ocean</span>
                    <a href="javascript:void(0);" class="ocean-plan-trigger" title="Ocean Plan">
                        <img src="<?php echo $this->basePath('img/ocean.png'); ?>" alt="Ocean Plan" width="90" height="90" />
                    </a>
                    <span class="price">Custom Price</span>
                </div>
            </div>
        </div>
    </div>
    
    <div class="checkout-form custom-form checkout-payment-form">
        <div class="subtitle">
            <h4 class="left">Card</h4>
            <span class="pay-pal-text right">or pay with <span class="pay-pal-action greyscale"></span></span>
        </div>
        <?php foreach ($form as $element): ?>
            <?php if (get_class($element) !== 'Zend\Form\Element\Radio'): ?>
                <div class="checkout-form-row custom-form-row custom-row-<?php echo $element->getName(); ?>">
                    <?php echo $this->formElement($element); ?>
                </div>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
    <?php echo $this->form()->closeTag() ?>
</section>
<script type="text/javascript">
    $(function(){
        SpreadPoint.Checkout.init();
    });
</script>
