<?php use Checkout\Helper\PlanHelper; ?>
<?php $helper = $this->planHelper(); ?>
<?php $plans = $helper->getAllPlans(); ?>

<section class="checkout-section">
    <?php
        $form = $this->form;
        $form->prepare();
        $form->setAttribute('action', $this->url('checkout',
            array('controller'=>'cart', 'action' => 'submit')));
        $form->setAttribute('method', 'post');
        $form->setAttribute('novalidate', 'novalidate');
        echo $this->form()->openTag($form);
    ?>
    
    <div class="checkout-form custom-form plan-form">
        <?php echo $this->partial('application/session/global-messages', array('global_messages' => $this->messages)); ?>
        <div class="checkout-form-row custom-form-row custom-row-plan">
            <div class="hidden-plan-element hide">
                <?php echo $this->formElement($form->get('plan')->setValue($this->plan)); ?>
            </div>
            <div class="visible-plan element">
                <div class="plan-puddle checkout-plan" data-value="<?php echo PlanHelper::PUDDLE_PLAN;?>">
                    <span class="title"><?php echo ucfirst($plans[PlanHelper::PUDDLE_PLAN]['name']); ?></span>
                    <a  href="javascript:void(0);" class="puddle-plan-trigger" title="<?php echo $plans[PlanHelper::PUDDLE_PLAN]['name'] ;?> Plan">
                        <img src="<?php echo $this->basePath($plans[PlanHelper::PUDDLE_PLAN]['image']); ?>" alt="<?php echo $plans[PlanHelper::PUDDLE_PLAN]['name'] ;?> Plan" width="100" height="100" />
                    </a>
                    <span class="price">$<?php echo ucfirst($plans[PlanHelper::PUDDLE_PLAN]['monthly']) ;?>/mo</span>
                    <span class="price">$<?php echo ucfirst($plans[PlanHelper::PUDDLE_PLAN]['yearly']) ;?>/yr</span>
                </div>
                <div class="plan-lake checkout-plan" data-value="<?php echo PlanHelper::LAKE_PLAN;?>">
                    <span class="title"><?php echo ucfirst($plans[PlanHelper::LAKE_PLAN]['name']); ?></span>                    
                    <a  href="javascript:void(0);" class="lake-plan-trigger" title="<?php echo $plans[PlanHelper::LAKE_PLAN]['name'] ;?> Plan">
                        <img src="<?php echo $this->basePath($plans[PlanHelper::LAKE_PLAN]['image']); ?>" alt="<?php echo $plans[PlanHelper::LAKE_PLAN]['name'] ;?> Plan" width="100" height="100" />
                    </a>
                    <span class="price">$<?php echo ucfirst($plans[PlanHelper::LAKE_PLAN]['monthly']) ;?>/mo</span>
                    <span class="price">$<?php echo ucfirst($plans[PlanHelper::LAKE_PLAN]['yearly']) ;?>/yr</span>
                </div>
                <div class="plan-ocean checkout-plan" data-value="<?php echo PlanHelper::OCEAN_PLAN;?>">
                    <span class="title"><?php echo ucfirst($plans[PlanHelper::OCEAN_PLAN]['name']); ?></span>
                    <a href="javascript:void(0);" class="ocean-plan-trigger" title="<?php echo $plans[PlanHelper::OCEAN_PLAN]['name'] ;?> Plan">
                        <img src="<?php echo $this->basePath($plans[PlanHelper::OCEAN_PLAN]['image']); ?>" alt="<?php echo $plans[PlanHelper::OCEAN_PLAN]['name'] ;?> Plan" width="90" height="90" />
                    </a>
                    <span class="price double">Custom Pricing to Fit Your Busines</span>
                </div>
            </div>
            <div class="period-element element">
                <div class="row">
                    <label class="period-label"><i class="fa fa-calendar"></i>Billing Period:</label>
                </div>
                <div class="row">
                    <input id="monthly" type="radio" name="period" required="required" class="kalypsify" value="0">
                    <label for="monthly">Monthly</label>
                </div>
                <div class="row">
                    <input id="yearly" type="radio" name="period" required="required" class="kalypsify" value="1">
                    <label for="yearly">Yearly</label>            
                </div>
            </div>
            <div class="plan-action">
                <button type="button" class="upgrade-plan-action">Upgrade Plan</button>
            </div>
        </div>
    </div>
    
    <div class="checkout-payment-form custom-form upgrade-payment-form hide">
        <div class="subtitle">
            <h4 class="left">Card</h4>
            <span class="pay-pal-text right">or pay with <span class="pay-pal-action greyscale"></span></span>
        </div>
        <?php foreach ($form as $element): ?>
            <?php if (get_class($element) !== 'Zend\Form\Element\Radio'): ?>
                <div class="checkout-form-row custom-form-row custom-row-<?php echo $element->getName(); ?>">
                    <?php echo $this->formElement($element); ?>
                </div>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
    <?php echo $this->form()->closeTag() ?>
</section>
<script type="text/javascript">
    $(function(){
        SpreadPoint.Checkout.init();
    });
</script>
