<div class="dashboard-menu-container">
    <ul class="dahsboard-menu">
        <li class="first">
            <a href="<?php echo $this->basePath('account'); ?>" class="dashboard-summary first <?php if ($this->selected == 'summary') { echo 'selected'; } ?>">
                <i class="fa fa-list"></i> Summary
            </a>
        </li>
        <li>
            <a href="<?php echo $this->basePath('campaign/list'); ?>" class="dashboard-campaign <?php if ($this->selected == 'campaigns') { echo 'selected'; } ?>">
                <i class="fa fa-bullseye"></i> Campaigns
            </a>
        </li>
        <li>
            <a href="<?php echo $this->basePath('campaign/entrants'); ?>" class="dashboard-entrants <?php if ($this->selected == 'entrants') { echo 'selected'; } ?>">
                <i class="fa fa-users"></i> Entrants
            </a>
        </li>
        <li>
            <a href="<?php echo $this->basePath('campaign/analysis'); ?>" class="dashboard-analysis <?php if ($this->selected == 'analysis') { echo 'selected'; } ?>">
                <i class="fa fa-bar-chart"></i> Analysis
            </a>
        </li>
        <li>
            <a href="<?php echo $this->basePath('account/support'); ?>" class="account-support <?php if ($this->selected == 'support') { echo 'selected'; } ?>">
                <i class="fa fa-support"></i> Support
            </a>
        </li>
        <li>
            <a href="<?php echo $this->basePath('checkout/cart/upgrade'); ?>" class="checkout-upgrade <?php if ($this->selected == 'upgrade') { echo 'selected'; } ?>">
                <i class="fa fa-arrow-up"></i> Upgrade
            </a>
        </li>
        <li>
            <a href="<?php echo $this->basePath('account/settings'); ?>" class="account-settings <?php if ($this->selected == 'settings') { echo 'selected'; } ?>">
                <i class="fa fa-gear"></i> Settings
            </a>
        </li>
        <li>
            <a href="<?php echo $this->basePath('account/logout'); ?>" class="account-logout">
                <i class="fa fa-power-off"></i> Log Out
            </a>
        </li>
    </ul>
</div>