<?php $helper = $this->campaignHelper(); ?>
<?php $helper->setData($this->data); ?>

<div class="banner">
    <img src="<?php echo $helper->getBannerUrl(); ?>" alt="<?php echo $helper->get('title'); ?>" />
</div>

<div class="hero">
    <h1 class="title" style="<?php echo $helper->get('titleCss'); ?>"><?php echo $helper->get('title'); ?></h1>
    <p class="description" style="<?php echo $helper->get('descriptionCss'); ?>"><?php echo $helper->get('description'); ?></p>
</div>

<div class="prizes">
    <?php $prizes = json_decode($this->prizeData); ?>
    <?php foreach ($prizes as $prize): ?>
        <div class="prize-container">
            <div class="prize-box" style="background-image: url(<?php echo $helper->getBannerUrl($this->campaign, $prize->image); ?>)">
                <span class="name">&nbsp;&nbsp;<?php echo $prize->name; ?></span>
            </div>
            <div class="prize-box-enlarged hide">
                <div class="enlarged-image prize-box-part">
                    <img src="<?php echo $helper->getBannerUrl($this->campaign, $prize->image); ?>" alt="<?php echo $prize->name; ?>" />
                    <div class="count-wrapper"><div class="count">x <?php echo $prize->count; ?></div></div>
                </div>
                <div class="content prize-box-part">
                    <h2>
                        <?php echo $prize->name; ?>
                    </h2>
                    <p><?php echo $prize->description; ?></p>
                    <span class="close"><i class="fa fa-close"></i></span>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>

<div class="widgets-container">
    <?php echo $this->partial('application/session/global-messages', array('global_messages' => $this->messages)); ?>

    <?php $entrant = $helper->getEntrant(); ?>
    <?php if ($entrant): ?>
        <div class="chance-entrant">
            <a href="<?php echo $this->basePath('campaign/clearSession/' . $this->data['id']); ?>" title="<?php echo $entrant->get('email'); ?>" />
                <span>Not <span><?php echo $entrant->get('name'); ?></span>?</span>
            </a>
        </div>
    <?php endif; ?>

    <div class="widgets jqui-accordion">
        <?php $widgets = json_decode($this->entriesData); ?>
        <?php foreach ($widgets as $widget): ?>
            <?php $template = $helper->getWidgetTemplate($widget->widgetType); ?>
            <?php echo $this->partial($template, array('data' => $widget, 'campaign' => $this->data)); ?>
        <?php endforeach; ?>
    </div>
    <div class="branding">
        <a href="<?php echo $helper->getDomain(); ?>" title="SpreadPoint" target="_blank">
            <span>Created with</span>
            <img src="<?php echo $this->basePath('img/logo.png') ?>" alt="SpreadPoint" height="20">
        </a>
    </div>
</div>

<script type="text/javascript">
    $(function() {
        SpreadPoint.Defaults.initializeAccordions();
        SpreadPoint.Defaults.initializeKalypto();
        
        $('.prize-box').each(function() {
            var self = $(this);
            var target = self.siblings('.prize-box-enlarged');
            
            var object = $.extend({}, SpreadPoint.PopUp);
            object.create(
                target, 
                self, 
                target.find('.close'), 
                false
            );
        });
    });
</script>