<div id="page" class="hfeed site">
    <section id="content" class="site-content">
        <section id="hero-header" data-speed="8" data-type="background"> 
            <div class="hero-content-container">
                <div class="hero-content">
                    <div class="hero-content-section hero-usp left">
                        <h2 class="animated fadeInDown delay">SPREAD THE WORD</h2> 
                        <h3 class="animated fadeInDown delay">WITH FULL CONTROL OVER YOUR MESSAGE</h3> 
                        <p class="animated fadeInDown delay">
                            Ce punem aici? Ce punem aici? Ce punem aici? Ce punem aici? Ce punem aici? Ce punem aici? Ce punem aici? Ce punem aici? Ce punem aici? Ce punem aici? Ce punem aici? Ce punem aici? Ce punem aici? Ce punem aici? Ce punem aici? Ce punem aici? Ce punem aici? Ce cacat punem aici?
                        </p>
                        <a href="<?php echo $this->basePath('pricing'); ?>" title="Start Your Free Trial" class="animated fadeInDown delay">
                            <input type="button" class="hero-button" value="Start Your Free Trial">
                        </a>
                    </div>
                    <div class="hero-content-section hero-register right animated fadeInDown delay">
                        <?php echo $this->partial('user/account/register.phtml', array('form' => new \User\Model\Form\RegisterForm())); ?>
                    </div>
                </div>
            </div>
        </section>
        
        <div class="home-services">
            <div class="grid grid-pad no-top"> 
                <div class="col-1-3 tri-clear wow animated fadeIn animated" data-wow-delay="0.25s" style="animation-delay: 0.25s; -webkit-animation-delay: 0.25s;"> 
                    <div class="service sbox-1">
                        <i class="fa fa-gift"></i>
                        <h5>Choose your prize</h5>
                        <p class="member-description">Anything from a thank you note to a plane. The more creative and bold the prize is, the more famous your challenge will be.</p>
                    </div>
                </div>
                <div class="col-1-3 tri-clear wow animated fadeIn animated" data-wow-delay="0.25s" style="animation-delay: 0.25s; -webkit-animation-delay: 0.25s;"> 
                    <div class="service sbox-2">
                        <i class="fa fa-comments"></i>
                        <h5>Start the movement</h5>
                        <p class="member-description">Share one link and then we do the rest. When your followers share the link, their chances to get your prize are increasing.</p>
                    </div>
                </div>
                <div class="col-1-3 tri-clear wow animated fadeIn animated" data-wow-delay="0.25s" style="animation-delay: 0.25s; -webkit-animation-delay: 0.25s;"> 
                    <div class="service sbox-3">
                        <i class="fa fa-users"></i>
                        <h5>Reach millions</h5>
                        <p class="member-description">Watch your brand gain visibility, expand from your current leads to their friends' friends and generate new followers.</p> 
                    </div>
                </div>
            </div>
        </div>

        <div class="strong-points">
            <div class="home-content intensity">
                <div class="grid">
                    <div class="strong-point-content">
                        <h2>Intensity over quantity</h2>
                        <p>
                            We focus, above all else, on generating loyal customers
                            because they are the minority that makes your company grow.
                        </p>
                    </div>
                </div>
            </div>
            <div class="home-content challenges">
                <div class="grid">
                    <div class="strong-point-content right">
                        <h2>Unique challenges</h2>
                        <p>
                            Change the way in which you engage <br /> your followers.
                        </p>
                    </div>
                </div>
            </div>
            <div class="home-content design">
                <div class="grid">
                    <div class="strong-point-content">
                        <h2>Personalized design</h2>
                        <p>
                            For enterprises we offer fully personalized campaign layouts.
                            From video backgrounds to animations in a timely and flexible
                            manner. There are no limits.
                        </p>
                    </div>
                </div>
            </div>
            <div class="home-content reach">
                <div class="grid">
                    <div class="strong-point-content right">
                        <h2>Unlimited reach</h2>
                        <p>
                            Your campaign can touch the eyes, <br /> ears and souls of millions.
                        </p>
                    </div>
                </div>
            </div>
            <div class="home-content control">
                <div class="grid">
                    <div class="strong-point-content right">
                        <p>all with...</p>
                        <h2>Full control over <br /> your message</h2>
                        <p>
                            You can reward your followers in many sifferent ways so they 
                            will help build your brand with enthusiasm.
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="home-cta">  
            <div class="grid grid-pad">
                <h2>Start knowing your customers.</h2>
                <div class="relative">
                    <span class="craby"></span>
                    <a href="<?php echo $this->basePath('pricing'); ?>" title="Start Your Free Trial">
                        <button>Sign up now - it's free for 30 days</button>
                    </a>
                </div>
            </div>
        </div>
    </section>
</div>