<div id="page" class="hfeed site">
    <section id="content" class="site-content">
        <section id="hero-header" data-speed="8" data-type="background"> 
            <div class="hero-content-container">
                <div class="hero-content">
                    <div class="hero-content-section hero-usp">
                        <h2 class="animated fadeInDown delay">SPREAD THE WORD</h2> 
                        <h3 class="animated fadeInDown delay">WITH FULL CONTROL OVER YOUR MESSAGE</h3> 
                        <p class="animated fadeInDown delay">
                            Through SpreadPoint you build enterprise-level raffles, 
                            contests, sweepstakes and giveaways for unrivaled reach 
                            and engagement.
                        </p>
                        <a href="<?php echo $this->basePath('checkout'); ?>" title="Start Your Free Trial" class="animated fadeInDown delay">
                            <input type="button" class="hero-button" value="Start Your Free Trial">
                        </a>
                        <a href="<?php echo $this->configHelper()->get('demo-url'); ?>" title="Live Demo" class="animated fadeInDown delay demo-link">
                            <input type="button" class="hero-button" value="Live Demo">
                        </a>
                    </div>
                </div>
            </div>
        </section>
        
        <div class="home-services">
            <div class="grid grid-pad no-top"> 
                <div class="col-1-3 tri-clear wow animated fadeIn animated" data-wow-delay="0.25s" style="animation-delay: 0.25s; -webkit-animation-delay: 0.25s;"> 
                    <div class="service sbox-1">
                        <i class="fa fa-gift"></i>
                        <h5>Choose your prize</h5>
                        <p class="member-description">Anything from a thank you note to a plane. The more creative and bold the prize is, the more famous your challenge will be.</p>
                    </div>
                </div>
                <div class="col-1-3 tri-clear wow animated fadeIn animated" data-wow-delay="0.25s" style="animation-delay: 0.25s; -webkit-animation-delay: 0.25s;"> 
                    <div class="service sbox-2">
                        <i class="fa fa-comments"></i>
                        <h5>Start the movement</h5>
                        <p class="member-description">Share one link and we do the rest! The more your followers invest in your brand, the bigger their chance gets to win the prize.</p>
                    </div>
                </div>
                <div class="col-1-3 tri-clear wow animated fadeIn animated" data-wow-delay="0.25s" style="animation-delay: 0.25s; -webkit-animation-delay: 0.25s;"> 
                    <div class="service sbox-3">
                        <i class="fa fa-users"></i>
                        <h5>Reach your audience</h5>
                        <p class="member-description">Watch your brand gain visibility, expand from your current leads to their friends' friends and generate new followers.</p> 
                    </div>
                </div>
            </div>
        </div>

        <div class="strong-points">
            <div class="strong-point-container">
                <div class="home-content intensity">
                    <div class="grid">
                        <div class="strong-point-content">
                            <h2>Intensity over quantity</h2>
                            <p>
                                We focus, above all else, on generating loyal customers! Why? Because they are the minority that makes your company grow.
                                <br />
                                <span class="show-more">Learn More</span>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="strong-point-details">
                    <div class="point-description">
                        <i class="fa fa-puzzle-piece"></i>
                        <h5>Beautiful Challenges</h5>
                        <p>
                            Our giveaway and promotion launching tool is easy 
                            to customize and lets you build both functionally 
                            and visually outstanding campaigns.
                        </p>
                    </div>
                    <div class="point-description">
                        <i class="fa fa-users"></i>
                        <h5>Understand your participants</h5>
                        <p>
                            SpreadPoint does not only offer Google Analytics integration, 
                            but comes with powerful data visualization tools that empower 
                            the reach and conversion rate of your challenge.
                        </p>
                    </div>
                    <div class="point-description">
                        <i class="fa fa-check"></i>
                        <h5>Recommendation System</h5>
                        <p>
                            What truly defines SpreadPoint is its recommendation system, 
                            which provides you with tips & tricks for increasing your 
                            campaign's engagement rating and for better targeting your 
                            desired user group.
                        </p>
                    </div>
                </div>
            </div>
            
            <div class="strong-point-container">
                <div class="home-content challenges">
                    <div class="grid">
                        <div class="strong-point-content right">
                            <h2>Unique challenges</h2>
                            <p>
                                Change the way in which you engage <br /> your followers.
                                <br />
                                <span class="show-more">Find out more</span>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="strong-point-details">
                    <div class="point-description">
                        <i class="fa fa-image"></i>
                        <h5>Video & Photo Contests</h5>
                        <p>
                            We go beyond standard raffles by letting you encourage 
                            your users to upload photographs or videos with them 
                            and your product for extra chances to win your prize. 
                        </p>
                    </div>
                    <div class="point-description">
                        <i class="fa fa-cube"></i>
                        <h5>Augmented Reality Contests</h5>
                        <p>
                            When innovative engagement is concerned, we stand 
                            out by offering augmented reality contests and raffles 
                            for our enterprise clients.
                        </p>
                    </div>
                    <div class="point-description">
                        <i class="fa fa-sliders"></i>
                        <h5>Create your own contest</h5>
                        <p>
                            With the Ocean plan, we will fully support your needs and 
                            build your ideal contest - just as you like it - for maximum 
                            engagement and creativity.
                        </p>
                    </div>
                </div>
            </div>
            
            <div class="strong-point-container">
                <div class="home-content design">
                    <div class="grid">
                        <div class="strong-point-content">
                            <h2>Personalized design</h2>
                            <p>
                                For enterprises we offer fully personalized campaign layouts.
                                From video backgrounds to animations in a timely and flexible
                                manner. There are no limits.
                                <br />
                                <span class="show-more">See How</span>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="strong-point-details">
                    <div class="point-description">
                        <i class="fa fa-code"></i>
                        <h5>Custom CSS</h5>
                        <p>
                            Build your campaign from scratch as you wish. SpreadPoint 
                            helps you with your most demanding requests by creating 
                            your favorite layouts from scratch or transforming your 
                            already built content into a running campaign.
                        </p>
                    </div>
                    <div class="point-description">
                        <i class="fa fa-film"></i>
                        <h5>Video Background</h5>
                        <p>
                            When standard is not enough, we give you the power 
                            to make your campaigns dynamic and insert your favorite 
                            video for better storytelling and user experience. 
                        </p>
                    </div>
                    <div class="point-description">
                        <i class="fa fa-flash"></i>
                        <h5>Animated Campaigns</h5>
                        <p>
                            SpreadPoint cares about the quality your participants 
                            receive from your challenge by making it alive and 
                            interactive at your request. 
                        </p>
                    </div>
                </div>
            </div>
            
            <div class="strong-point-container">
                <div class="home-content reach">
                    <div class="grid">
                        <div class="strong-point-content right">
                            <h2>Unlimited reach</h2>
                            <p>
                                Your campaign can touch the eyes, <br /> ears and souls of millions.
                                <br />
                                <span class="show-more">Learn More</span>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="strong-point-details">
                    <div class="point-description">
                        <i class="fa fa-user-plus"></i>
                        <h5>Unlimited Participants</h5>
                        <p>
                            We mean it! We will never restrict the amount of 
                            participants that can see or take part in your 
                            raffle or contest. 
                        </p>
                    </div>
                    <div class="point-description">
                        <i class="fa fa-bullhorn"></i>
                        <h5>Unlimited Campaigns</h5>
                        <p>
                            Same goes for the number of campaigns you can make 
                            either for yourself or for your clients. 
                        </p>
                    </div>
                    <div class="point-description">
                        <i class="fa fa-gift"></i>
                        <h5>Unlimited Prizes</h5>
                        <p>
                            Choose and give as many prizes as you wish. We do 
                            not limit the diversity and quantity of your prizes in any way.
                        </p>
                    </div>
                </div>
            </div>
            
            <div class="home-content control">
                <div class="grid">
                    <div class="strong-point-content right">
                        <p>all with...</p>
                        <h2>Full control over <br /> your message</h2>
                        <p>
                            You can reward your followers in many different ways so they 
                            will help build your brand with enthusiasm.
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="home-cta">  
            <div class="grid grid-pad">
                <h2>Start engaging your customers.</h2>
                <div class="relative">
                    <span class="craby"></span>
                    <a href="<?php echo $this->basePath('checkout'); ?>" title="Start Your Free Trial">
                        <button>Sign up now - it's free for 30 days</button>
                    </a>
                </div>
            </div>
        </div>
    </section>
</div>
<script type="text/javascript">
    (function() {
        $('.show-more').on('click', function() {
            $(this).closest('.strong-point-container')
                .find('.strong-point-details')
                .slideToggle();
        });
    })();
</script>