<?php use User\Model\Form\RegisterForm; ?>
<div id="page" class="hfeed site">
    <section id="content" class="site-content">
        <section id="hero-header" data-speed="8" data-type="background"> 
            <div class="hero-content-container">
                <div class="hero-content">
                    <div class="hero-content-section hero-usp left">
                        <h2 class="animated fadeInDown delay">SPREAD THE WORD</h2> 
                        <h3 class="animated fadeInDown delay">WITH FULL CONTROL OVER YOUR MESSAGE</h3> 
                    </div>
                    <div class="hero-content-section hero-register right animated fadeInDown delay">
                        <?php echo $this->partial('user/account/register.phtml', array('form' => new RegisterForm())); ?>
                    </div>
                </div>
            </div>
        </section>
        
        <div class="home-services">
            <div class="grid grid-pad no-top"> 
                <div class="col-1-3 tri-clear wow animated fadeIn animated" data-wow-delay="0.25s" style="animation-delay: 0.25s; -webkit-animation-delay: 0.25s;"> 
                    <div class="service sbox-1">
                        <i class="fa fa-gift"></i>
                        <h5>Choose your prize</h5>
                        <p class="member-description">Anything from a thank you note to a plane. The more creative and bold the prize is, the more famous your challenge will be.</p>
                    </div>
                </div>
                <div class="col-1-3 tri-clear wow animated fadeIn animated" data-wow-delay="0.25s" style="animation-delay: 0.25s; -webkit-animation-delay: 0.25s;"> 
                    <div class="service sbox-2">
                        <i class="fa fa-comments"></i>
                        <h5>Start the movement</h5>
                        <p class="member-description">Share one link and then we do the rest. When your followers share the link, their chances to get your prize are increasing.</p>
                    </div>
                </div>
                <div class="col-1-3 tri-clear wow animated fadeIn animated" data-wow-delay="0.25s" style="animation-delay: 0.25s; -webkit-animation-delay: 0.25s;"> 
                    <div class="service sbox-3">
                        <i class="fa fa-users"></i>
                        <h5>Reach millions</h5>
                        <p class="member-description">Watch your brand gain visibility, expand from your current leads to their friends' friends and generate new followers.</p> 
                    </div>
                </div>
            </div>
        </div>

        <div class="home-content background-light">
            <div class="grid">
                <div class="strong-point">
                    <div class="strong-point-text">
                        <h2>Intensity over quantity</h2>
                        <p>Our main focus is to help you aquire and built loyal customers instead of getting a large number of mediocre feelings.</p>
                    </div>
                    <div class="strong-point-image">
                        <img src="<?php echo $this->basePath('img/puddle.png'); ?>" alt="Puddle Package" width="200" height="200" class="alignnone size-medium wp-image-48" />
                    </div>
                </div>
            </div>
        </div>
        
        <div class="home-content">
            <div class="grid">
                <div class="strong-point">
                    <div class="strong-point-image">
                        <img src="<?php echo $this->basePath('img/puddle.png'); ?>" alt="Puddle Package" width="200" height="200" class="alignnone size-medium wp-image-48" />
                    </div>
                    <div class="strong-point-text">
                        <h2>Information is power</h2>
                        <p>It's called the information era for a reason. One of our most powerful feature is the ability to easily interpret a lots of data.</p>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="home-content background-light">
            <div class="grid">
                <div class="strong-point">
                    <div class="strong-point-text pad-top-50">
                        <h2>Ease of learning</h2>
                        <p>Our goal is to bring you and your customers closer. With SpreadPoint you can easily learn how your customers think and addapt to their needs instantly.</p>
                    </div>
                    <div class="strong-point-image">
                        <img src="<?php echo $this->basePath('img/puddle.png'); ?>" alt="Puddle Package" width="200" height="200" class="alignnone size-medium wp-image-48" />
                    </div>
                </div>
            </div>
        </div>
        
        <div class="home-content">
            <div class="grid">
                <div class="strong-point">
                    <div class="strong-point-image">
                        <img src="<?php echo $this->basePath('img/puddle.png'); ?>" alt="Puddle Package" width="200" height="200" class="alignnone size-medium wp-image-48" />
                    </div>
                    <div class="strong-point-text">
                        <h2>You can't lose money</h2>
                        <p>Our pricing system is built on a performance base, so there is no way for you to lose money. How much is a loyal customer worth to you?</p>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="home-content background-light">
            <div class="grid">
                <div class="strong-point">
                    <div class="strong-point-text">
                        <h2>We are very young</h2>
                        <p>We only launched recently, so you have our full atention at your disposition and will always be special to us.</p>
                    </div>
                    <div class="strong-point-image">
                        <img src="<?php echo $this->basePath('img/puddle.png'); ?>" alt="Puddle Package" width="200" height="200" class="alignnone size-medium wp-image-48" />
                    </div>
                </div>
            </div>
        </div>
        
        <div class="home-content">
            <div class="grid">
                <div class="strong-point">
                    <div class="strong-point-image">
                        <img src="<?php echo $this->basePath('img/puddle.png'); ?>" alt="Puddle Package" width="200" height="200" class="alignnone size-medium wp-image-48" />
                    </div>
                    <div class="strong-point-text pad-top-50">
                        <h2>So Why choose us?</h2>
                        <p>We have the highest conversion rates, the best data analysis tools and you have a guaranteed profit. You probably want to work with us already so start changing your business now!</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="home-cta">  
            <div class="grid grid-pad">
                <div class="sensible-home-widget-area" id="subscribe">
                    <div class="col-1-1">
                        <aside id="newsletterwidget" class="widget widget_newsletterwidget">
                            <h6>Request Early Access</h6>
                            <script type="text/javascript">
                            //<![CDATA[
                                if (typeof newsletter_check !== "function") {
                                    window.newsletter_check = function(f) {
                                        var re = /^([a-zA-Z0-9_\.\-\+])+\@(([a-zA-Z0-9\-]{1,})+\.)+([a-zA-Z0-9]{2,})+$/;
                                        if (!re.test(f.elements["ne"].value)) {
                                            alert("The email is not correct");
                                            return false;
                                        }
                                        if (f.elements["nn"] && (f.elements["nn"].value == "" || f.elements["nn"].value == f.elements["nn"].defaultValue)) {
                                            alert("The name is not correct");
                                            return false;
                                        }
                                        for (var i = 1; i < 20; i++) {
                                            if (f.elements["np" + i] && f.elements["np" + i].value == "") {
                                                alert("");
                                                return false;
                                            }
                                        }
                                        if (f.elements["ny"] && !f.elements["ny"].checked) {
                                            alert("You must accept the privacy statement");
                                            return false;
                                        }
                                        return true;
                                    }
                                }
                            //]]>
                            </script>

                            <div class="newsletter newsletter-widget">
                                <script type="text/javascript">
                                //<![CDATA[
                                    if (typeof newsletter_check !== "function") {
                                        window.newsletter_check = function(f) {
                                            var re = /^([a-zA-Z0-9_\.\-\+])+\@(([a-zA-Z0-9\-]{1,})+\.)+([a-zA-Z0-9]{2,})+$/;
                                            if (!re.test(f.elements["ne"].value)) {
                                                alert("The email is not correct");
                                                return false;
                                            }
                                            if (f.elements["nn"] && (f.elements["nn"].value == "" || f.elements["nn"].value == f.elements["nn"].defaultValue)) {
                                                alert("The name is not correct");
                                                return false;
                                            }
                                            for (var i = 1; i < 20; i++) {
                                                if (f.elements["np" + i] && f.elements["np" + i].value == "") {
                                                    alert("");
                                                    return false;
                                                }
                                            }
                                            if (f.elements["ny"] && !f.elements["ny"].checked) {
                                                alert("You must accept the privacy statement");
                                                return false;
                                            }
                                            return true;
                                        }
                                    }
                                //]]>
                                </script>

                                <form action="<?php echo $this->basePath('newsletter/subscribe'); ?>" onsubmit="return newsletter_check(this)" method="post">
                                    <input type="hidden" name="nr" value="widget">
                                        <p>
                                            <input class="newsletter-firstname" type="text" name="nn" value="Name" onclick="if (this.defaultValue == this.value)
                                                this.value = ''" onblur="if (this.value == '')
                                                    this.value = this.defaultValue">
                                        </p>
                                        <p>
                                            <input class="newsletter-email" type="email" required="" name="ne" value="Email" onclick="if (this.defaultValue == this.value)
                                                this.value = ''" onblur="if (this.value == '')
                                                    this.value = this.defaultValue">
                                        </p>
                                        <p>
                                            <input class="newsletter-profile newsletter-profile-1" type="text" name="np1" value="Website" onclick="if (this.defaultValue == this.value)
                                                this.value = ''" onblur="if (this.value == '')
                                                    this.value = this.defaultValue"></p><p><input class="newsletter-submit" type="submit" value="I Want In">
                                        </p>
                                </form>
                            </div>
                        </aside> 
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
<script type="text/javascript">
    $(function(){
        $('.toggle-menu').jPushMenu();
    });
</script>