<?php use Checkout\Helper\PlanHelper; ?>
<?php $helper = $this->planHelper(); ?>
<?php $plans = $helper->getAllPlans(); ?>
<div class="pricing-container">
    <div class="pricing-header">
        <div class="pricing-header-content">
            <h2>Engage Your Customers in a Unique Way</h2>
            <p>Create your first campaign now and see precisely how your message spreads around the world. Sign up and start gaining loyal followers within minutes. For real!</p>
            <a href="<?php echo $this->basePath('checkout'); ?>" title="Try It Now For Free">
               <input class="pricing" type="submit" value="Try It Now For Free">
            </a>
        </div>
    </div>
    <div class="pricing-section">
        <div class="option-puddle option wow animated fadeInLeft animated">
            <div class="option-image">
                <img src="<?php echo $this->basePath($plans[PlanHelper::PUDDLE_PLAN]['image']); ?>" alt="<?php echo ucfirst($plans[PlanHelper::PUDDLE_PLAN]['name']) ;?> Plan" width="100" height="100" />
            </div>
            <div class="option-title">
                <p><?php echo $plans[PlanHelper::PUDDLE_PLAN]['name'] ;?> Plan</p>
            </div>
            <div class="option-price">
                <h4>$<?php echo ucfirst($plans[PlanHelper::PUDDLE_PLAN]['monthly']) ;?>/MO</h4>
                <h4>$<?php echo ucfirst($plans[PlanHelper::PUDDLE_PLAN]['yearly']) ;?>/YR<br /><span>*save 2 months</span></h4>
            </div>
            <div class="option-benefits">
                <ul class="benefits">
                    <li>Unlimited campaigns</li>
                    <li>Reward Facebook distribution</li>
                    <li>Reward Twitter distribution</li>
                    <li>Reward E-mail distribution</li>
                    <li>Share a direct link to your campaign</li>
                    <li>Export all your data</li>
                    <li>Email Notifications</li>
                    <li>Multiple winners</li>
                </ul>
                <h5>Comming Soon..</h5>
                <ul class="comming-soon">
                    <li>Embed campaigns on your website</li>
                    <li>Email integrations</li>
                    <li>Reward Google+ distribution</li>
                    <li>Reward LinkedIn distribution</li>
                    <li>Reward Pinterest distribution</li>
                    <li>Reward Instagram distribution</li>
                    <li>Reward YouTube distribution</li>
                    <li>Real Time Data Analysis</li>
                </ul>
            </div>
            <div class="option-buy">
                <a href="<?php echo $this->basePath('checkout?package=' . PlanHelper::PUDDLE_PLAN); ?>" class="featured-link">
                    <button class="wow animated" style="visibility: visible;">Get Started For Free</button>
                </a>
            </div>
        </div>
        <div class="option-lake option wow animated fadeInLeft animated">
            <div class="option-image">
                <img src="<?php echo $this->basePath($plans[PlanHelper::LAKE_PLAN]['image']); ?>" alt="<?php echo ucfirst($plans[PlanHelper::LAKE_PLAN]['name']) ;?> Plan" width="150" height="150">
            </div>         
            <div class="option-title">
                <p><?php echo $plans[PlanHelper::LAKE_PLAN]['name'] ;?> Plan</p>
            </div>         
            <div class="option-price">             
                <h4>$<?php echo ucfirst($plans[PlanHelper::LAKE_PLAN]['monthly']) ;?>/MO</h4>
                <h4>
                    $<?php echo ucfirst($plans[PlanHelper::LAKE_PLAN]['yearly']) ;?>/YR
                    <br />
                    <span>*save 2 months</span>
                </h4>
                
            </div>
            <div class="option-benefits">
                <ul class="benefits">
                    <li>Everything from the "Puddle" package</li>
                    <li>Age restriction</li>
                    <li>Less Branding</li>
                    <li>Custom Emails</li>
                    <li>Reward for referrals</li>
                </ul>
                <h5>Comming Soon..</h5>
                <ul class="comming-soon">
                    <li>Custom forms</li>
                    <li>Photo Contests</li>
                    <li>Reward for sharing a Video</li>
                    <li>Reward for completing a survey</li>
                    <li>Restrict by location</li>
                </ul>
            </div> 	
            <div class="option-buy"> 	                 
                <a href="<?php echo $this->basePath('checkout?package=' . PlanHelper::LAKE_PLAN); ?>" class="featured-link">                 
                    <button class="wow animated">Get Started For Free</button>             
                </a>
            </div>     
        </div>  
        <div class="option-ocean option wow animated fadeInLeft animated">
            <div class="option-image">
                <img src="<?php echo $this->basePath($plans[PlanHelper::OCEAN_PLAN]['image']); ?>" alt="<?php echo ucfirst($plans[PlanHelper::OCEAN_PLAN]['name']) ;?> Plan" width="100" height="100">
            </div>
            <div class="option-title">
                <p><?php echo $plans[PlanHelper::OCEAN_PLAN]['name'] ;?> Plan</p>
            </div>
            <div class="option-price">
                <h4>&nbsp;</h4>
                <h4>
                    Custom Pricing
                    <br />
                    <span>to Fit Your Business</span>
                </h4>
            </div>
            <div class="option-benefits">
                <ul class="benefits">
                    <li>Everything from the "Lake" package</li>
                    <li>Priority support</li>
                    <li>Dedicated Agent</li>
                    <li>Customizable campaigns</li>
                    <li>Personalized distribution</li>
                    <li>Custom Branding</li>
                    <li>Personalzied Recommendations</li>
                </ul>
            </div>
            <div class="option-buy">
                <a href="<?php echo $this->basePath('contact'); ?>" class="featured-link">             
                    <button class="wow animated">Drop Us a Line</button>         
                </a>
            </div>     
        </div>	
    </div>
</div>
<div class="grid grid-pad no-top"></div>















