<div class="pricing-container">
    <div class="pricing-header">
        <div class="pricing-header-content">
            <h2>Engage Your Customers in a Unique Way</h2>
            <p>Create your first campaign now and see precisely how your message spreads around the world. Sign up and start gaining loyal followers within minutes. For real!</p>
            <a href="<?php echo $this->basePath('checkout'); ?>" title="Try It Now For Free">
               <input class="pricing" type="submit" value="Try It Now For Free">
            </a>
        </div>
    </div>
    <div class="pricing-section">  
        <div class="option-puddle option wow animated fadeInLeft animated">
            <div class="option-image">
                <img src="<?php echo $this->basePath('img/puddle.png'); ?>" alt="Puddle Package" width="200" height="200" class="alignnone size-medium wp-image-48" />
            </div>
            <div class="option-title">
                <p>Puddle Package</p>
            </div>
            <div class="option-price">
                <h1>$19/month</h1>
                <h1>$189/year</h1>
            </div>
            <div class="option-benefits">
                <ul class="benefits">
                    <li>Reach up to 1000 people</li>
                    <li>Unlimited campaigns</li>
                    <li>Short company description</li>
                    <li>Reward Facebook distribution</li>
                    <li>Reward Twitter distribution</li>
                    <li>Reward E-mail distribution</li>
                    <li>Share a direct link to your campaign</li>
                    <li>Embed campaigns on your website</li>
                </ul>
            </div>
            <div class="option-buy">
                <a href="<?php echo $this->basePath('checkout?package=puddle'); ?>" class="featured-link">
                    <button class="wow animated" style="visibility: visible;">Get Started For Free</button>
                </a>
                <p class="satisfaction-guarantee"><strong>100% money back guaranteed</strong>. If you are not satisfied you get all your money back, <strong>no questions asked!</strong></p>
            </div>
        </div>
        <div class="option-lake option wow animated fadeInLeft animated">
            <div class="option-image">
                <img src="<?php echo $this->basePath('img/lake.png'); ?>" alt="Lake Package" width="300" height="300" class="alignnone size-medium wp-image-47">
            </div>         
            <div class="option-title">
                <p>Lake Package</p>
            </div>         
            <div class="option-price">             
                <h1>$129/month</h1>
                <h1>$1289/year</h1>
            </div>
            <div class="option-benefits">
                <ul class="benefits">
                    <li>Everything from the "Puddle" package</li>
                    <li>Reach up to 10000 people</li>
                    <li>Share a direct link to your campaign</li>
                    <li>Add video on your company description</li>
                    <li>Reward for watching a video</li>
                    <li>Reward for answering a question</li>
                    <li>Reward for choosing a picture</li>
                    <li>Reward for visiting a website</li>
                    <li>Reward for uploading an image or a video</li>
                    <li>Real time data analysis</li>
                </ul>
            </div> 	
            <div class="option-buy"> 	                 
                <a href="<?php echo $this->basePath('checkout?package=lake'); ?>" class="featured-link">                 
                    <button class="wow animated">Get Started For Free</button>             
                </a>
                <p class="satisfaction-guarantee"><strong>100% money back guaranteed</strong>. If you are not satisfied you get all your money back, <strong>no questions asked!</strong></p>
            </div>     
        </div>  
        <div class="option-ocean option wow animated fadeInLeft animated">
            <div class="option-image">
                <img src="<?php echo $this->basePath('img/ocean.png'); ?>" alt="Ocean Package" width="300" height="300" class="alignnone size-medium wp-image-46">
            </div>
            <div class="option-title">
                <p>Ocean Package</p>
            </div>
            <div class="option-price">
                <h1>Custom Price</h1>
            </div>
            <div class="option-benefits">
                <ul class="benefits">
                    <li>Everything from the "Lake" package</li>
                    <li>Unlimited reach</li>
                    <li>Priority support</li>
                    <li>Customizable campaigns</li>
                    <li>Personalized distribution</li>
                </ul>
            </div>
            <div class="option-buy">
                <a href="<?php echo $this->basePath('contact'); ?>" class="featured-link">             
                    <button class="wow animated">Drop Us a Line</button>         
                </a>
                <p class="satisfaction-guarantee"><strong>100% money back guaranteed</strong>. If you are not satisfied you get all your money back, <strong>no questions asked!</strong></p>
            </div>     
        </div>	
    </div>
</div>
<div class="grid grid-pad no-top"></div>















