<div class="privacy-policy cms-page">

    <!--Privacy Policy-->
    <h4>Privacy Policy</h4>
    <p>
        Here at SpreadPoint, your privacy very is important to us. This Policy covers the way 
        in which we will use or will not use the information we collect from our Clients (contest 
        creators) or Participants (people who take part in contests) and the types of 
        information we will or we won’t collect.
    </p>

    <p>We do not:</p>
    <ol>
        <li>
            Sell or distribute personal information to 3rd parties such as your name or 
            e-mail address.
        </li>

        <li>
            Share personal information with anyone for purposes others than developing 
            our service, protecting our rights or complying with the law and regulations. 
        </li>

        <li>
            Ask for personal information unless we need it to develop and provide our services. 
        </li>

        <li>
            Store credit card information.
        </li>

        <li>
            Store personal information on our infrastructure for reasons others than 
            the delivery of our services.
        </li>
    </ol>

    <p>
        The type of information SpreadPoint collects is non-personally identifying 
        and we use this information for understanding the way in which visitors interact 
        with our site. The type of data we collect includes the browser type, language 
        preferences, IP addresses, source site and the time of visit. 
        Moreover, we may release an aggregation of such non-personally identifiable data in 
        the form of trend analyses in the usage of the website that may be used for 
        promotional purposes.
    </p>

    
    
    <!--Collection of Information-->
    <h4>Collection of Information</h4>
    <p>
        The minimum age for a Participants to interact with campaigns created with SpreadPoint 
        is 13 years old. If you are under 13 years old, please do not submit any personal data.
    </p>
    <p>
        When a Participant joins a giveaway created with SpreadPoint, we record the IP 
        address of the Participant and distribute it to the Client responsible with the 
        administration of such contest/raffle, with the intention of helping him moderate 
        giveaway entries. This gives an administrator a way to limit entrants per IP address, 
        household or region.
    </p>
    <p>
        We may collect additional information relate to Clients that intend to 
        acquire one of our packages. In this scenario, Clients are asked to provide extra 
        information including personal and financial information required for processing 
        those transactions. Also, we may whare Client's contact information if request by 
        a participant.
    </p>
    <p>
        SpreadPoint collects such information only with the purpose of supporting the 
        visitor's scope of interaction with the site. We do not disclose this 
        personally-identifying information other than described below and visitors 
        always have the right to refuse to supply such information while acknowledging 
        that such action may prevent the user from engaging with certain areas.
    </p>
    <p>
        Any information that we collect may be stored on servers provided by 3rd party 
        hosting vendors with whom we work under a contract.
    </p>
    <p>
        SpreadPoint collects information from any Participant that enters a SpreadPoint 
        giveaway. This information is presented to the Client – the giveaway administrator 
        for assisting him/her in managing the contest and make moderation tasks easier. 
        Moreover, SpreadPoint offers the Client the option to download a list of entries.
    </p>
    <p>
        Some giveaways created with SpreadPoint and used on a 3rd party platform might 
        contain additional Privacy Policy stipulations and therefore, we urge you to 
        carefully consider these before registering. Participants are responsible for 
        taking customary precautions to guard against "malware". If you have any reason 
        to believe the giveaway administrator is using this list maliciously, please 
        contact us at support@spreadpoint.co.
    </p>

    
    
    <!--Statistics and use of collected data-->
    <h4>Statistics and use of collected data</h4>
    <p>
        We may collect statistics about the visitors behavior on SpreadPoint. 
        For example, we may monitor the most appealing prizes or the most frequented 
        giveaways on SpreadPoint. This data may be used for providing Clients with 
        data analysis gather feedback and improve our service offering. Moreover, Google 
        Analytics is installed on our site and has the purpose of collecting similar 
        information for service enhancement purposes.
    </p>

    
    
    <!--Protection of Data-->
    <h4>Protection of Data</h4>
    <p>
        We disclose personally-identifying information only to those whose employees, 
        contractors and affiliated organizations need to know that information in order 
        to process it on SpreadPoint’s behalf or to provide services available at 
        SpreadPoint Site with the obligation and agreement not to disclose it to others.
    </p>
    <p>
        As an example, if you’re having trouble with choosing a winner (whether that 
        is a user error or a bug on our end) and you file a support ticket, an employee 
        of SpreadPoint may access your account to help decide how to best remedy the 
        solution. This might include opening up your list of entries and seeing entrant 
        information.
    </p>
    <p>
        If you are a registered user of SpreadPoint and have supplied your email 
        address, we may send you an email to tell you about new features, solicit your 
        feedback, or just keep you up to date with what’s going on with SpreadPoint and 
        our products. SpreadPoint takes all measures reasonably necessary to protect 
        against the unauthorized access, use, alteration or destruction of potentially 
        personally-identifying information.
    </p>

    
    <!--Use of cookies-->
    <h4>Use of cookies</h4>
    <p>
        SpreadPoint uses cookies for identifying and tracking Participants and Clients, 
        their usage of SpreadPoint, and their website access preferences. In the event 
        in which Participants and Clients do not wish to have cookies placed on their 
        computers, they should set their browsers to refuse them before using SpreadPoint. 
        Moreover, the Participants and Clients that choose to do this acknowledge that 
        such actions might negatively impact the functionality of the website.
    </p>

    
    <!--Changes in Privacy Policy-->
    <h4>Changes in Privacy Policy</h4>
    <p>
        SpreadPoint may change its Privacy Policy from time to time at its sole discretion. 
        We strongly encourage visitors to frequently check this page for any changes to our 
        Privacy Policy. Your continued use of this site after any change 
        in this Privacy Policy will constitute your acceptance of such change.
    </p>
    
    
    <!--How to Contact Us-->
    <h4>How to Contact Us</h4>
    <p>
        Should you have other questions or concerns about these privacy policies, please send 
        us an email at support@spreadpoint.co
    </p>
</div>
