<div class="terms-of-service">
    
    <!--Intro-->
    <h4>SpreadPoint Terms of Service</h4>
    <p>
        We (SpreadPoint) are a web service that allows you to engage consumers by creating 
        and running giveaways. By using SpreadPoint, you subject to the following
        terms of service ("Terms"). Your continuous use of SpreadPoint means that you accept these terms. 
        If you do not agree to the present terms you must stop using SpreadPoint.
    </p>
    <p>
        Our service can include administrative messages from SpreadPoint, announcements and 
        other forms of communication which are considered part of our membership program. 
        New features that complement or enhance the current service are subject to the terms.
        Moreover, you accept and agree that the service is provided "as-is" and that you, as the
        account owner, are fully responsible for all data within your account. SpreadPoint does 
        not take responsibility for the deletion, failure to store information or settings, 
        timeliness or misdelivery.
    </p>

    
    <!--General-->
    <h4>General Conditions</h4>
    <p>
        We promote a safe and responsible use of SpreadPoint and as a condition to your use of 
        SpreadPoint, you should not: 
    </p>

    <ol>
        <li>Run a competition without the intention of giving out a prize</li>
        <li>Provide illegal or false name, email address or any other information when you sign up.</li>
        <li>Maliciously use the information collected through SpreadPoint such as names, 
            e-mail addresses, or any other information.</li>

        <li>Use SpreadPoint for any illegal or unauthorized action, including and not limited to 
            copyright laws.</li>

        <li>Make available any materials, information or content that is illegal, harmful, 
            threatening, obscene, harassing, defamatory, offensive, privacy invasive or 
            that promotes bigotry, racism, hatred, harm against individuals or groups of individuals.</li>

        <li>Manipulate elements of the website for affecting the content transmitted through 
            SpreadPoint</li>

        <li>Impersonate another person or company</li>
        <li>Use copyrighted material from any third-party without their consent</li>

        <li>Use bots or crawlers on the SpreadPoint domain</li>

        <li>Disobey any requirements, procedures, policies or regulations of networks that 
            are connected to SpreadPoint</li>

        <li>Falsely imply that another site is associated with SpreadPoint</li>

        <li>Reproduce, duplicate, copy, exploit, reverse engineer  or disassemble any of the
            software used to support and maintain SpreadPoint</li>

        <li>Forge headers or manipulate the transmited data to gain an unfair advantage in advantage
            in a competition or harm the competition owner</li>

        <li>Reproduce, duplicate or modify any part of SpreadPoint without approval</li>
    </ol>

    <p>
        Security and availability of our Service is fundamental for delivering our services 
        excellently. We are ambitioned to keep your data secured, anonymous 
        and private. Some elements that are out of our timely and direct control such as your
        internet service provider, hosting services, internet intermediaries and other service 
        providers cannot be assured. Although we strive to eliminate any possible risk, you 
        accept the possibility of such occurrences to happen and the responsibility of choosing 
        and using a technology which is not 100% reliable.  
    </p>
    <p>
        SpreadPoint is an internet-based self-service and is not responsible for the success of 
        your promotion. While we may offer recommendations on the type of prizes to 
        use or the ideal target group for your current prizes based on the data we extract 
        anonymously, they are purely informative and we do not take any responsibility for 
        any loss that occurred as a consequence of following them. SpreadPoint does not 
        provide refunds or credits for a promotion that performed poorly or not as expected. 
    </p>
    <p>
        Clients launch promotions and giveaways from our Site and Participants may choose to 
        take part in them. You, as a Participant, acknowledge that the Clients are the ones 
        responsible to verify that the challenges and giveaways they launch and distribute 
        through the site are compliant to the applicable rules, laws and regulations. Before 
        entering a promotion created with SpreadPoint, we strongly encourage you to read the 
        Terms of Service and Privacy Policy, together with any additional information 
        provided by the Client or SpreadPoint. Moreover, you fully 
        acknowledge that SpreadPoint is not responsible or liable for the failure of any Client
        or 3rd party to comply with the terms of usage, policies and applicable laws, 
        rules or regulations that govern any giveaway or promotion. 
    </p>
    <p>
        In the event in which the Clients require you to provide personally identifiable 
        information as a prerequisite to participating in their promotions and you choose to 
        provide it to them, SpreadPoint may use any such information as mentioned in these 
        Terms of Service and you fully acknowledge and agree with this. Moreover, you agree 
        that in the case in which such Clients use the information you provide for personal 
        use or distribution, SpreadPoint is not liable.
    </p>
    <p>
        If you are a Client who administrates a giveaway or promotion, you understand that 
        SpreadPoint does not provide any assurance for guaranteeing the compliance of your
        promotions and media with any rule, regulation, policy, terms and laws, and you fully 
        acknowledge and agree with this. Any such  verification will be done by the Client and
        you in the quality of a Client, are responsible with the compliance with any promises
        made to Participants, except the cases in which such promises violate the law, rules and
        regulations.
    </p>

    
    <!--Billing-->
    <h4>Billing</h4>
    <p>
        SpreadPoint accepts credit cards as a payment method and will charge your credit card 
        automatically, depending on your payment preferences, monthly or yearly.
        In case any fee is not paid in a timely manner, or your transaction cannot be processed 
        by SpreadPoint with the credit card information you provided, we reserve the right to 
        revoke or suspend your account.
    </p>
    <p>
        The fees representing your chosen package will be billed in advance, from the date you 
        purchase the package and on each monthly or yearly renewal thereafter until you 
        cancel your account. 
    </p>
    <p>
        The service is billed in advance and we accept no refunds or credits for partial
        months or years of service, upgrade/downgrade refunds. All fees are exclusive of taxes 
        and duties imposed by the authorities and you shall be responsible for payment of all 
        such taxes and duties.
    </p>
    <p>
        For any upgrade or downgrade in your plan, your credit card that you provided 
        will automatically be charged the new rate on your next billing cycle. Downgrading
        your service may cause the loss of content or features of your account. SpreadPoint 
        will not be responsible for any such loss.
    </p>
    <p>
        Your subscription will automatically be renewed and you authorize us to collect 
        the respective annual or monthly subscription fee using any credit card or other 
        payment mechanism you initially provided, unless you notify SpreadPoint before 
        the end of the applicable subscription period that you want to cancel your plan. 
    </p>
    <p>
        You are solely responsible for cancelling your account, which you can do at any time 
        by making a request at support@spreadpoint.co.
    </p>

    
    
    <!--Copyright-->
    <h4>Copyright Infringement</h4>
    <p>
        If you believe that materials exist on SpreadPoint that violate your copyright, you are 
        encouraged to contact us. We take such notices seriously and a response is guaranteed. 
        The outcome varies from the removal of the reported content to the disabling of all the 
        links that lead to the infringing content. In the case in which repeat copyright 
        infringements occur, SpreadPoint reserves the right to terminate the Client's access
        to SpreadPoint, without offering a reimbursement for the period left in the
        contract or any compensation related to such action.
    </p>
    <p>
        SpreadPoint does not endorse, sponsor or administer the content of any promotion, 
        challenge, competition, contest or giveaway distributed through its platform and is
        not liable. 
    </p>

    
    <!--Modifications-->
    <h4>Modifications to the Service and Prices</h4>
    <p>
        SpreadPoint reserves the right to change or modify any terms of service contained 
        on this domain at any time. You agree and acknowledge that it is your responsibility
        to review this section. Your continued use of SpreadPoint after such modifications took 
        place will constitute an acknowledgment on your side of the updated Terms and 
        Conditions.
    </p>
    <p>
        SpreadPoint has the right to amend fees for current services at its discretion. 
        For any such changes, a notice will be provided to you through your accounts e-mail 
        address at least 30 days prior to the changes and will take effect starting with the 
        next billing cycle.
    </p>

    
    
    <!--Liability-->
    <h4>Liability Limitation</h4>
    <p>
        SpreadPoint is not liable, in any event, with respect to any 
        subject matter present in this agreement, under any contract, negligence or other legal
        theory for any special, incidental or consequential damages, the cost of procurement
        for substitute products or services, for interruption of use or loss / corruption of
        data or for any amounts that exceed the fees paid by you to SpreadPoint, as stipulated 
        under this agreement. SpreadPoint will have no liability for any failure or delay due to matters beyond their
        reasonable control. 
    </p>
    
    
    <!--Termination-->
    <h4>Termination of Use</h4>
    <p>
        We may terminate your access to any and all parts of the Site at any time with or
        without cause or notice, effective immediately. If you wish to cancel this 
        agreement account you can simply stop using SpreadPoint.
    </p>

    
    <!--Warranty-->
    <h4>Warranty</h4>
    <p>
        Neither SpreadPoint nor its licensors or suppliers makes any warranty that the
        website will be error free or that access to the Site will be uninterrupted or 
        continuous. 
    </p>

    
    <!--License-->
    <h4>License and Ownership</h4>
    <p>
        You agree not to make derivative tools based on SpreadPoint and you agree not 
        to reverse engineer or use SpreadPoint with the intent of producing a competitive
        product or service. Moreover, you acknowledge and agree that SpreadPoint owns all 
        the rights and interest in SpreadPoint Site, including its intellectual property rights,
        features, functions and graphics. 
    </p>

    <br />
    <p>Copyright &copy; SpreadPoint 2015</p>
</div>